
SCRIPTS=auto \
	adduser \
	bootconfig \
	checksum \
	cheri-desktop \
	cheri-vm-support \
	config \
	docsinstall \
	entropy \
	fetchmissingdists \
	finalconfig \
	hardening \
	hostname \
	jail \
	keymap \
	mirrorselect \
	mount \
	netconfig \
	netconfig_ipv4 \
	netconfig_ipv6 \
	rootpass \
	script \
	services \
	time \
	umount \
	wlanconfig \
	zfsboot

BINDIR= ${LIBEXECDIR}/bsdinstall

MAN=

.include <bsd.prog.mk>
