SHLIB=	cheribsdtest_dynamic
PRIVATELIB=
MAN=	# No manpage; this is internal.

SRCS=	cheribsdtest_dynamic_fptr.c					\
	cheribsdtest_dynamic_identity_cap.c				\
	cheribsdtest_dynamic_ifunc.c					\
	cheribsdtest_dynamic_tls.c

.include <bsd.lib.mk>
