# $FreeBSD$

freebsd_instance:
  # image: freebsd-12-1-stable-amd64
  # We need a newer image to install llvm11
  image_family: freebsd-12-1-snap
  cpu: 8
  memory: 24G

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  timeout_in: 120m
  install_script:
  - pkg install -y llvm11
  setup_script:
  - uname -a
  - df -m
  - pw useradd user
  - mkdir -p /usr/obj/$(pwd -P)
  - chown user:user /usr/obj/$(pwd -P)
  script:
  - su user -c "make -j$(sysctl -n hw.ncpu) CROSS_TOOLCHAIN=llvm11 WITHOUT_TOOLCHAIN=yes buildworld buildkernel"
  post_script:
  - df -m
  - du -m -s /usr/obj
