/*-
 * SPDX-License-Identifier: BSD-2-Clause
 *
 * Copyright (c) 2021 Ruslan Bukin <br@bsdpad.com>
 *
 * This work was supported by Innovate UK project 105694, "Digital Security
 * by Design (DSbD) Technology Platform Prototype".
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 *
 * $FreeBSD$
 */

#ifndef _DEV_DRM_PANFROST_FEATURES_H_
#define _DEV_DRM_PANFROST_FEATURES_H_

enum panfrost_hw_feature {
	HW_FEATURE_JOBCHAIN_DISAMBIGUATION,
	HW_FEATURE_PWRON_DURING_PWROFF_TRANS,
	HW_FEATURE_XAFFINITY,
	HW_FEATURE_OUT_OF_ORDER_EXEC,
	HW_FEATURE_MRT,
	HW_FEATURE_BRNDOUT_CC,
	HW_FEATURE_INTERPIPE_REG_ALIASING,
	HW_FEATURE_LD_ST_TILEBUFFER,
	HW_FEATURE_MSAA_16X,
	HW_FEATURE_32_BIT_UNIFORM_ADDRESS,
	HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL,
	HW_FEATURE_OPTIMIZED_COVERAGE_MASK,
	HW_FEATURE_T7XX_PAIRING_RULES,
	HW_FEATURE_LD_ST_LEA_TEX,
	HW_FEATURE_LINEAR_FILTER_FLOAT,
	HW_FEATURE_WORKGROUP_ROUND_MULTIPLE_OF_4,
	HW_FEATURE_IMAGES_IN_FRAGMENT_SHADERS,
	HW_FEATURE_TEST4_DATUM_MODE,
	HW_FEATURE_NEXT_INSTRUCTION_TYPE,
	HW_FEATURE_BRNDOUT_KILL,
	HW_FEATURE_WARPING,
	HW_FEATURE_V4,
	HW_FEATURE_FLUSH_REDUCTION,
	HW_FEATURE_PROTECTED_MODE,
	HW_FEATURE_COHERENCY_REG,
	HW_FEATURE_PROTECTED_DEBUG_MODE,
	HW_FEATURE_AARCH64_MMU,
	HW_FEATURE_TLS_HASHING,
	HW_FEATURE_THREAD_GROUP_SPLIT,
	HW_FEATURE_3BIT_EXT_RW_L2_MMU_CONFIG,
};

#define hw_features_t600 (\
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_V4))

#define hw_features_t620 (\
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_V4))

#define hw_features_t720 (\
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_OPTIMIZED_COVERAGE_MASK) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_WORKGROUP_ROUND_MULTIPLE_OF_4) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_V4))


#define hw_features_t760 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT))

#define hw_features_t860 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT))

#define hw_features_t880 hw_features_t860

#define hw_features_t830 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT))

#define hw_features_t820 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT))

#define hw_features_g71 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_FLUSH_REDUCTION) | \
	(1 << HW_FEATURE_PROTECTED_MODE) | \
	(1 << HW_FEATURE_COHERENCY_REG))

#define hw_features_g72 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_FLUSH_REDUCTION) | \
	(1 << HW_FEATURE_PROTECTED_MODE) | \
	(1 << HW_FEATURE_PROTECTED_DEBUG_MODE) | \
	(1 << HW_FEATURE_COHERENCY_REG))

#define hw_features_g51 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_FLUSH_REDUCTION) | \
	(1 << HW_FEATURE_PROTECTED_MODE) | \
	(1 << HW_FEATURE_PROTECTED_DEBUG_MODE) | \
	(1 << HW_FEATURE_COHERENCY_REG))

#define hw_features_g52 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_FLUSH_REDUCTION) | \
	(1 << HW_FEATURE_PROTECTED_MODE) | \
	(1 << HW_FEATURE_PROTECTED_DEBUG_MODE) | \
	(1 << HW_FEATURE_COHERENCY_REG))

#define hw_features_g76 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_FLUSH_REDUCTION) | \
	(1 << HW_FEATURE_PROTECTED_MODE) | \
	(1 << HW_FEATURE_PROTECTED_DEBUG_MODE) | \
	(1 << HW_FEATURE_COHERENCY_REG) | \
	(1 << HW_FEATURE_AARCH64_MMU) | \
	(1 << HW_FEATURE_TLS_HASHING) | \
	(1 << HW_FEATURE_3BIT_EXT_RW_L2_MMU_CONFIG))

#define hw_features_g31 (\
	(1 << HW_FEATURE_JOBCHAIN_DISAMBIGUATION) | \
	(1 << HW_FEATURE_PWRON_DURING_PWROFF_TRANS) | \
	(1 << HW_FEATURE_XAFFINITY) | \
	(1 << HW_FEATURE_WARPING) | \
	(1 << HW_FEATURE_INTERPIPE_REG_ALIASING) | \
	(1 << HW_FEATURE_32_BIT_UNIFORM_ADDRESS) | \
	(1 << HW_FEATURE_ATTR_AUTO_TYPE_INFERRAL) | \
	(1 << HW_FEATURE_BRNDOUT_CC) | \
	(1 << HW_FEATURE_BRNDOUT_KILL) | \
	(1 << HW_FEATURE_LD_ST_LEA_TEX) | \
	(1 << HW_FEATURE_LD_ST_TILEBUFFER) | \
	(1 << HW_FEATURE_LINEAR_FILTER_FLOAT) | \
	(1 << HW_FEATURE_MRT) | \
	(1 << HW_FEATURE_MSAA_16X) | \
	(1 << HW_FEATURE_NEXT_INSTRUCTION_TYPE) | \
	(1 << HW_FEATURE_OUT_OF_ORDER_EXEC) | \
	(1 << HW_FEATURE_T7XX_PAIRING_RULES) | \
	(1 << HW_FEATURE_TEST4_DATUM_MODE) | \
	(1 << HW_FEATURE_THREAD_GROUP_SPLIT) | \
	(1 << HW_FEATURE_FLUSH_REDUCTION) | \
	(1 << HW_FEATURE_PROTECTED_MODE) | \
	(1 << HW_FEATURE_PROTECTED_DEBUG_MODE) | \
	(1 << HW_FEATURE_COHERENCY_REG) | \
	(1 << HW_FEATURE_AARCH64_MMU) | \
	(1 << HW_FEATURE_TLS_HASHING) | \
	(1 << HW_FEATURE_3BIT_EXT_RW_L2_MMU_CONFIG))

static inline bool panfrost_has_hw_feature(struct panfrost_softc *sc,
    enum panfrost_hw_feature feat)
{
	if (sc->features.hw_features & (1 << feat))
		return (true);

	return (false);
}

#endif /* _DEV_DRM_PANFROST_FEATURES_H_ */
