.\"
.\" Copyright (c) 2022 Edward Tomasz Napierala <en322@cl.cam.ac.uk>
.\" All rights reserved.
.\"
.\" This software was developed by the University of Cambridge Computer
.\" Laboratory as part of the CHERI for Hypervisors and Operating Systems
.\" (CHaOS) project, funded by EPSRC grant EP/V000292/1.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd May 25, 2022
.Dt COLOOKUP 1
.Os
.Sh NAME
.Nm colookup
.Nd insert public capability into capability vector
.Sh SYNOPSIS
.Nm
.Fl c Ar name
.Nm
.Op Fl v
.Fl n Ar name Fl i Ar index
.Op Fl n Ar name Fl i Ar index Ar ...
.Ar command Op Ar args ...
.Nm
.Op Fl v
.Fl f Ar path Fl i Ar index
.Op Fl f Ar path Fl i Ar index Ar ...
.Ar command Op Ar args ...
.Nm
.Fl s
.Sh DESCRIPTION
The
.Nm
utility uses
.Xr colookup 2
to find named public capability and spawns
.Ar command
with that capability passed in its inherited capability vector.
.Pp
Note that for capability passing to work,
.Nm
must be colocated with the
.Xr coregister 1
instance on the other end.
Typically this will happen automatically, but if not, one can manually
colocate
.Nm
using
.Xr coexec 1 .
.Pp
The following options are available:
.Bl -tag -width ".Fl ii"
.It Fl c
Instead of spawning anything, print out the capability value and exit.
.It Fl f
File system path to the
.Xr unix 4
socket to receive the capability from.
.It Fl i
Capability vector table index to insert the new entry at.
.It Fl n
Name of the capability to insert; see
.Xr coregister 1 .
.It Fl s
Instead of spawning anything, print out the sealed pairs returned by
.Xr cosetup 2 .
.It Fl v
Be verbose.
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh EXAMPLES
To spawn a shell with
.Nm
public capability named
.Qq fabulous
inserted at offset 5 in its inherited capability vector,
and then show the vector:
.Pp
.Dl colookup -n fabulous -i 5 sh
.Dl capv
.Pp
.Sh SEE ALSO
.Xr capv 1 ,
.Xr coexec 1 ,
.Xr coregister 1 ,
.Xr colookup 2 ,
.Xr capv 7
.Sh HISTORY
The
.Nm
command appeared in
.Tn CheriBSD .
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was developed by
.An Edward Tomasz Napierala Aq Mt trasz@FreeBSD.org
at the University of Cambridge Computer Laboratory as part of the CHERI
for Hypervisors and Operating Systems (CHaOS) project, funded by EPSRC
grant EP/V000292/1.
