NEED_COMPAT=	64CB
.include <bsd.compat.mk>

PROG=	ld-elf64cb-c18n.so.1
MAN=
MLINKS=	rtld.1 ld-elf64cb-c18n.so.1.1

RTLD_SANDBOX_ALWAYS=

.PATH:  ${SRCTOP}/libexec/rtld-elf
.include "${SRCTOP}/libexec/rtld-elf/Makefile"
