# FreeBSD system call object files.
# DO NOT EDIT-- this file is automatically @generated.
# $FreeBSD$
MIASM =  \
	syscall.o \
	exit.o \
	fork.o \
	freebsd64_read.o \
	freebsd64_write.o \
	freebsd64_open.o \
	close.o \
	freebsd64_wait4.o \
	freebsd64_link.o \
	freebsd64_unlink.o \
	freebsd64_chdir.o \
	fchdir.o \
	freebsd11_freebsd64_mknod.o \
	freebsd64_chmod.o \
	freebsd64_chown.o \
	freebsd64_break.o \
	getpid.o \
	freebsd64_mount.o \
	freebsd64_unmount.o \
	setuid.o \
	getuid.o \
	geteuid.o \
	freebsd64_ptrace.o \
	freebsd64_recvmsg.o \
	freebsd64_sendmsg.o \
	freebsd64_recvfrom.o \
	freebsd64_accept.o \
	freebsd64_getpeername.o \
	freebsd64_getsockname.o \
	freebsd64_access.o \
	freebsd64_chflags.o \
	fchflags.o \
	sync.o \
	kill.o \
	getppid.o \
	dup.o \
	freebsd10_pipe.o \
	getegid.o \
	freebsd64_profil.o \
	freebsd64_ktrace.o \
	getgid.o \
	freebsd64_getlogin.o \
	freebsd64_setlogin.o \
	freebsd64_acct.o \
	freebsd64_sigaltstack.o \
	freebsd64_ioctl.o \
	reboot.o \
	freebsd64_revoke.o \
	freebsd64_symlink.o \
	freebsd64_readlink.o \
	freebsd64_execve.o \
	umask.o \
	freebsd64_chroot.o \
	freebsd64_msync.o \
	vfork.o \
	sbrk.o \
	sstk.o \
	freebsd11_vadvise.o \
	freebsd64_munmap.o \
	freebsd64_mprotect.o \
	freebsd64_madvise.o \
	freebsd64_mincore.o \
	freebsd64_getgroups.o \
	freebsd64_setgroups.o \
	getpgrp.o \
	setpgid.o \
	freebsd64_setitimer.o \
	freebsd64_swapon.o \
	freebsd64_getitimer.o \
	getdtablesize.o \
	dup2.o \
	freebsd64_fcntl.o \
	freebsd64_select.o \
	fsync.o \
	setpriority.o \
	socket.o \
	freebsd64_connect.o \
	getpriority.o \
	freebsd64_bind.o \
	freebsd64_setsockopt.o \
	listen.o \
	freebsd64_gettimeofday.o \
	freebsd64_getrusage.o \
	freebsd64_getsockopt.o \
	freebsd64_readv.o \
	freebsd64_writev.o \
	freebsd64_settimeofday.o \
	fchown.o \
	fchmod.o \
	setreuid.o \
	setregid.o \
	freebsd64_rename.o \
	flock.o \
	freebsd64_mkfifo.o \
	freebsd64_sendto.o \
	shutdown.o \
	freebsd64_socketpair.o \
	freebsd64_mkdir.o \
	freebsd64_rmdir.o \
	freebsd64_utimes.o \
	freebsd64_adjtime.o \
	setsid.o \
	freebsd64_quotactl.o \
	freebsd64_nlm_syscall.o \
	freebsd64_nfssvc.o \
	freebsd64_lgetfh.o \
	freebsd64_getfh.o \
	freebsd64_sysarch.o \
	freebsd64_rtprio.o \
	freebsd64_semsys.o \
	freebsd64_msgsys.o \
	freebsd64_shmsys.o \
	setfib.o \
	freebsd64_ntp_adjtime.o \
	setgid.o \
	setegid.o \
	seteuid.o \
	freebsd11_freebsd64_stat.o \
	freebsd11_freebsd64_fstat.o \
	freebsd11_freebsd64_lstat.o \
	freebsd64_pathconf.o \
	fpathconf.o \
	freebsd64_getrlimit.o \
	freebsd64_setrlimit.o \
	freebsd11_freebsd64_getdirentries.o \
	__syscall.o \
	freebsd64___sysctl.o \
	freebsd64_mlock.o \
	freebsd64_munlock.o \
	freebsd64_undelete.o \
	freebsd64_futimes.o \
	getpgid.o \
	freebsd64_poll.o \
	freebsd7_freebsd64___semctl.o \
	semget.o \
	freebsd64_semop.o \
	freebsd7_freebsd64_msgctl.o \
	msgget.o \
	freebsd64_msgsnd.o \
	freebsd64_msgrcv.o \
	freebsd64_shmat.o \
	freebsd7_freebsd64_shmctl.o \
	freebsd64_shmdt.o \
	shmget.o \
	freebsd64_clock_gettime.o \
	freebsd64_clock_settime.o \
	freebsd64_clock_getres.o \
	freebsd64_ktimer_create.o \
	ktimer_delete.o \
	freebsd64_ktimer_settime.o \
	freebsd64_ktimer_gettime.o \
	ktimer_getoverrun.o \
	freebsd64_nanosleep.o \
	freebsd64_ffclock_getcounter.o \
	freebsd64_ffclock_setestimate.o \
	freebsd64_ffclock_getestimate.o \
	freebsd64_clock_nanosleep.o \
	freebsd64_clock_getcpuclockid2.o \
	freebsd64_ntp_gettime.o \
	freebsd64_minherit.o \
	rfork.o \
	issetugid.o \
	freebsd64_lchown.o \
	freebsd64_aio_read.o \
	freebsd64_aio_write.o \
	freebsd64_lio_listio.o \
	freebsd64_kbounce.o \
	freebsd64_flag_captured.o \
	freebsd11_freebsd64_getdents.o \
	freebsd64_lchmod.o \
	freebsd64_lutimes.o \
	freebsd11_freebsd64_nstat.o \
	freebsd11_freebsd64_nfstat.o \
	freebsd11_freebsd64_nlstat.o \
	freebsd64_preadv.o \
	freebsd64_pwritev.o \
	freebsd64_fhopen.o \
	freebsd11_freebsd64_fhstat.o \
	modnext.o \
	freebsd64_modstat.o \
	modfnext.o \
	freebsd64_modfind.o \
	freebsd64_kldload.o \
	kldunload.o \
	freebsd64_kldfind.o \
	kldnext.o \
	freebsd64_kldstat.o \
	kldfirstmod.o \
	getsid.o \
	setresuid.o \
	setresgid.o \
	freebsd64_aio_return.o \
	freebsd64_aio_suspend.o \
	freebsd64_aio_cancel.o \
	freebsd64_aio_error.o \
	yield.o \
	mlockall.o \
	munlockall.o \
	freebsd64___getcwd.o \
	freebsd64_sched_setparam.o \
	freebsd64_sched_getparam.o \
	freebsd64_sched_setscheduler.o \
	sched_getscheduler.o \
	sched_yield.o \
	sched_get_priority_max.o \
	sched_get_priority_min.o \
	freebsd64_sched_rr_get_interval.o \
	freebsd64_utrace.o \
	freebsd64_kldsym.o \
	freebsd64_jail.o \
	freebsd64_nnpfs_syscall.o \
	freebsd64_sigprocmask.o \
	freebsd64_sigsuspend.o \
	freebsd64_sigpending.o \
	freebsd64_sigtimedwait.o \
	freebsd64_sigwaitinfo.o \
	freebsd64___acl_get_file.o \
	freebsd64___acl_set_file.o \
	freebsd64___acl_get_fd.o \
	freebsd64___acl_set_fd.o \
	freebsd64___acl_delete_file.o \
	__acl_delete_fd.o \
	freebsd64___acl_aclcheck_file.o \
	freebsd64___acl_aclcheck_fd.o \
	freebsd64_extattrctl.o \
	freebsd64_extattr_set_file.o \
	freebsd64_extattr_get_file.o \
	freebsd64_extattr_delete_file.o \
	freebsd64_aio_waitcomplete.o \
	freebsd64_getresuid.o \
	freebsd64_getresgid.o \
	kqueue.o \
	freebsd11_freebsd64_kevent.o \
	freebsd64_extattr_set_fd.o \
	freebsd64_extattr_get_fd.o \
	freebsd64_extattr_delete_fd.o \
	__setugid.o \
	freebsd64_eaccess.o \
	afs3_syscall.o \
	freebsd64_nmount.o \
	freebsd64___mac_get_proc.o \
	freebsd64___mac_set_proc.o \
	freebsd64___mac_get_fd.o \
	freebsd64___mac_get_file.o \
	freebsd64___mac_set_fd.o \
	freebsd64___mac_set_file.o \
	freebsd64_kenv.o \
	freebsd64_lchflags.o \
	freebsd64_uuidgen.o \
	freebsd64_sendfile.o \
	freebsd64_mac_syscall.o \
	freebsd11_freebsd64_getfsstat.o \
	freebsd11_freebsd64_statfs.o \
	freebsd11_freebsd64_fstatfs.o \
	freebsd11_freebsd64_fhstatfs.o \
	ksem_close.o \
	ksem_post.o \
	ksem_wait.o \
	ksem_trywait.o \
	freebsd64_ksem_init.o \
	freebsd64_ksem_open.o \
	freebsd64_ksem_unlink.o \
	freebsd64_ksem_getvalue.o \
	ksem_destroy.o \
	freebsd64___mac_get_pid.o \
	freebsd64___mac_get_link.o \
	freebsd64___mac_set_link.o \
	freebsd64_extattr_set_link.o \
	freebsd64_extattr_get_link.o \
	freebsd64_extattr_delete_link.o \
	freebsd64___mac_execve.o \
	freebsd64_sigaction.o \
	freebsd64_sigreturn.o \
	freebsd64_getcontext.o \
	freebsd64_setcontext.o \
	freebsd64_swapcontext.o \
	freebsd64_swapoff.o \
	freebsd64___acl_get_link.o \
	freebsd64___acl_set_link.o \
	freebsd64___acl_delete_link.o \
	freebsd64___acl_aclcheck_link.o \
	freebsd64_sigwait.o \
	freebsd64_thr_create.o \
	freebsd64_thr_exit.o \
	freebsd64_thr_self.o \
	thr_kill.o \
	jail_attach.o \
	freebsd64_extattr_list_fd.o \
	freebsd64_extattr_list_file.o \
	freebsd64_extattr_list_link.o \
	freebsd64_ksem_timedwait.o \
	freebsd64_thr_suspend.o \
	thr_wake.o \
	kldunloadf.o \
	freebsd64_audit.o \
	freebsd64_auditon.o \
	freebsd64_getauid.o \
	freebsd64_setauid.o \
	freebsd64_getaudit.o \
	freebsd64_setaudit.o \
	freebsd64_getaudit_addr.o \
	freebsd64_setaudit_addr.o \
	freebsd64_auditctl.o \
	freebsd64__umtx_op.o \
	freebsd64_thr_new.o \
	freebsd64_sigqueue.o \
	freebsd64_kmq_open.o \
	freebsd64_kmq_setattr.o \
	freebsd64_kmq_timedreceive.o \
	freebsd64_kmq_timedsend.o \
	freebsd64_kmq_notify.o \
	freebsd64_kmq_unlink.o \
	freebsd64_abort2.o \
	freebsd64_thr_set_name.o \
	freebsd64_aio_fsync.o \
	freebsd64_rtprio_thread.o \
	sctp_peeloff.o \
	freebsd64_sctp_generic_sendmsg.o \
	freebsd64_sctp_generic_sendmsg_iov.o \
	freebsd64_sctp_generic_recvmsg.o \
	freebsd64_pread.o \
	freebsd64_pwrite.o \
	freebsd64_mmap.o \
	lseek.o \
	freebsd64_truncate.o \
	ftruncate.o \
	thr_kill2.o \
	freebsd12_freebsd64_shm_open.o \
	freebsd64_shm_unlink.o \
	freebsd64_cpuset.o \
	cpuset_setid.o \
	freebsd64_cpuset_getid.o \
	freebsd64_cpuset_getaffinity.o \
	freebsd64_cpuset_setaffinity.o \
	freebsd64_faccessat.o \
	freebsd64_fchmodat.o \
	freebsd64_fchownat.o \
	freebsd64_fexecve.o \
	freebsd11_freebsd64_fstatat.o \
	freebsd64_futimesat.o \
	freebsd64_linkat.o \
	freebsd64_mkdirat.o \
	freebsd64_mkfifoat.o \
	freebsd11_freebsd64_mknodat.o \
	freebsd64_openat.o \
	freebsd64_readlinkat.o \
	freebsd64_renameat.o \
	freebsd64_symlinkat.o \
	freebsd64_unlinkat.o \
	posix_openpt.o \
	freebsd64_gssd_syscall.o \
	freebsd64_jail_get.o \
	freebsd64_jail_set.o \
	jail_remove.o \
	freebsd12_closefrom.o \
	freebsd64___semctl.o \
	freebsd64_msgctl.o \
	freebsd64_shmctl.o \
	freebsd64_lpathconf.o \
	freebsd64___cap_rights_get.o \
	cap_enter.o \
	freebsd64_cap_getmode.o \
	freebsd64_pdfork.o \
	pdkill.o \
	freebsd64_pdgetpid.o \
	freebsd64_pselect.o \
	freebsd64_getloginclass.o \
	freebsd64_setloginclass.o \
	freebsd64_rctl_get_racct.o \
	freebsd64_rctl_get_rules.o \
	freebsd64_rctl_get_limits.o \
	freebsd64_rctl_add_rule.o \
	freebsd64_rctl_remove_rule.o \
	posix_fallocate.o \
	posix_fadvise.o \
	freebsd64_wait6.o \
	freebsd64_cap_rights_limit.o \
	freebsd64_cap_ioctls_limit.o \
	freebsd64_cap_ioctls_get.o \
	cap_fcntls_limit.o \
	freebsd64_cap_fcntls_get.o \
	freebsd64_bindat.o \
	freebsd64_connectat.o \
	freebsd64_chflagsat.o \
	freebsd64_accept4.o \
	freebsd64_pipe2.o \
	freebsd64_aio_mlock.o \
	freebsd64_procctl.o \
	freebsd64_ppoll.o \
	freebsd64_futimens.o \
	freebsd64_utimensat.o \
	fdatasync.o \
	freebsd64_fstat.o \
	freebsd64_fstatat.o \
	freebsd64_fhstat.o \
	freebsd64_getdirentries.o \
	freebsd64_statfs.o \
	freebsd64_fstatfs.o \
	freebsd64_getfsstat.o \
	freebsd64_fhstatfs.o \
	freebsd64_mknodat.o \
	freebsd64_kevent.o \
	freebsd64_cpuset_getdomain.o \
	freebsd64_cpuset_setdomain.o \
	freebsd64_getrandom.o \
	freebsd64_getfhat.o \
	freebsd64_fhlink.o \
	freebsd64_fhlinkat.o \
	freebsd64_fhreadlink.o \
	freebsd64_funlinkat.o \
	freebsd64_copy_file_range.o \
	freebsd64___sysctlbyname.o \
	freebsd64_shm_open2.o \
	freebsd64_shm_rename.o \
	freebsd64_sigfastblock.o \
	freebsd64___realpathat.o \
	close_range.o \
	freebsd64_rpctls_syscall.o
