.\"
.\" Copyright (c) 2018 Edward Tomasz Napierala <en322@cl.cam.ac.uk>
.\" All rights reserved.
.\"
.\" This software was developed by SRI International and the University of
.\" Cambridge Computer Laboratory under DARPA/AFRL contract (FA8750-10-C-0237)
.\" ("CTSRD"), as part of the DARPA CRASH research programme.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd November 20, 2020
.Dt COPING 1
.Os
.Sh NAME
.Nm coping
.Nd colocated ping
.Sh SYNOPSIS
.Nm
.Fl a
.Op Fl c Ar count
.Op Fl k
.Op Fl s Ar time
.Op Fl v
.Nm
.Fl i Ar index
.Op Fl c Ar count
.Op Fl k
.Op Fl s Ar time
.Op Fl v
.Nm
.Op Fl c Ar count
.Op Fl k
.Op Fl s Ar time
.Op Fl v
.Ar target-name
.Op Ar ...
.Sh DESCRIPTION
The
.Nm
utility is used to send colocated pings; usually used with
.Xr copong 1 .
.Pp
The following options are available:
.Bl -tag -width "c Ar count"
.It Fl a
Ping all services found in the capability vector inherited
from the parent process.
.It Fl c Ar count
Exit after
.Ar count
iterations.
.It Fl i
Ping service found at offset
.Ar index
in the capability vector inherited from the parent process.
.It Fl k
Use
.Xr cocall_slow 2
instead of trying
.Xr cocall 2
first.
.It Fl s Ar time
Number of seconds to pause between iterations; can be zero.
.It Fl v
Be verbose.
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.Sh EXAMPLES
Measure the time for 1000 pings to each service found in
.Xr capv 7 :
.Pp
.Dl coping -ac 1000
.Pp
.Sh SEE ALSO
.Xr capv 1 ,
.Xr copong 1 ,
.Xr cocall 2 ,
.Xr capv 7
.Sh HISTORY
The
.Nm
command appeared in
.Tn CheriBSD .
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was developed by
.An Edward Tomasz Napierala Aq Mt trasz@FreeBSD.org
at the University of Cambridge Computer Laboratory under DARPA/AFRL contract
(FA8750-10-C-0237) ("CTSRD"), as part of the DARPA CRASH research programme.
