/*
 * Public system call stubs provided by libsys.
 *
 * Do not use directly, include <libsys.h> instead.
 *
 *  DO NOT EDIT-- this file is automatically @generated.
 */
#ifndef __LIBSYS_H_
#define __LIBSYS_H_

#include <sys/_cpuset.h>
#include <sys/_domainset.h>
#include <sys/_ffcounter.h>
#include <sys/_semaphore.h>
#include <sys/_sigaltstack.h>
#include <machine/ucontext.h>   /* for mcontext_t */
#include <sys/_ucontext.h>
#include <sys/wait.h>

struct __siginfo;
struct __ucontext;
struct __wrusage;
struct acl;
struct aiocb;
struct auditinfo;
struct auditinfo_addr;
struct cheri_revoke_syscall_info;
struct ffclock_estimate;
struct fhandle;
struct iovec;
struct itimerspec;
struct itimerval;
struct jail;
struct kevent;
struct kld_file_stat;
struct mac;
struct module_stat;
struct mq_attr;
struct msghdr;
struct msqid_ds;
struct ntptimeval;
struct pollfd;
struct rlimit;
struct rtprio;
struct rusage;
struct sched_param;
struct sctp_sndrcvinfo;
struct sembuf;
struct sf_hdtr;
struct shmid_ds;
struct sigaction;
struct sigaltstack;
struct sigevent;
struct sockaddr;
struct spacectl_range;
struct stat;
struct statfs;
struct thr_param;
struct timespec;
struct timeval;
struct timex;
struct timezone;
struct uuid;
union semun;

__BEGIN_DECLS
typedef void (__sys_exit_t)(int);
typedef int (__sys_fork_t)(void);
typedef ssize_t (__sys_read_t)(int, void * __kerncap, size_t);
typedef ssize_t (__sys_write_t)(int, const void * __kerncap, size_t);
typedef int (__sys_open_t)(const char * __kerncap, int, mode_t);
typedef int (__sys_close_t)(int);
typedef int (__sys_wait4_t)(int, int * __kerncap, int, struct rusage * __kerncap);
typedef int (__sys_link_t)(const char * __kerncap, const char * __kerncap);
typedef int (__sys_unlink_t)(const char * __kerncap);
typedef int (__sys_chdir_t)(const char * __kerncap);
typedef int (__sys_fchdir_t)(int);
typedef int (__sys_chmod_t)(const char * __kerncap, mode_t);
typedef int (__sys_chown_t)(const char * __kerncap, int, int);
typedef void * (__sys_break_t)(char * __kerncap);
typedef pid_t (__sys_getpid_t)(void);
typedef int (__sys_mount_t)(const char * __kerncap, const char * __kerncap, int, void * __kerncap);
typedef int (__sys_unmount_t)(const char * __kerncap, int);
typedef int (__sys_setuid_t)(uid_t);
typedef uid_t (__sys_getuid_t)(void);
typedef uid_t (__sys_geteuid_t)(void);
typedef int (__sys_ptrace_t)(int, pid_t, char * __kerncap, int);
typedef ssize_t (__sys_recvmsg_t)(int, struct msghdr * __kerncap, int);
typedef ssize_t (__sys_sendmsg_t)(int, const struct msghdr * __kerncap, int);
typedef ssize_t (__sys_recvfrom_t)(int, void * __kerncap, size_t, int, struct sockaddr * __kerncap, __socklen_t * __kerncap);
typedef int (__sys_accept_t)(int, struct sockaddr * __kerncap, __socklen_t * __kerncap);
typedef int (__sys_getpeername_t)(int, struct sockaddr * __kerncap, __socklen_t * __kerncap);
typedef int (__sys_getsockname_t)(int, struct sockaddr * __kerncap, __socklen_t * __kerncap);
typedef int (__sys_access_t)(const char * __kerncap, int);
typedef int (__sys_chflags_t)(const char * __kerncap, u_long);
typedef int (__sys_fchflags_t)(int, u_long);
typedef int (__sys_sync_t)(void);
typedef int (__sys_kill_t)(int, int);
typedef pid_t (__sys_getppid_t)(void);
typedef int (__sys_dup_t)(u_int);
typedef gid_t (__sys_getegid_t)(void);
typedef int (__sys_profil_t)(char * __kerncap, size_t, size_t, u_int);
typedef int (__sys_ktrace_t)(const char * __kerncap, int, int, int);
typedef gid_t (__sys_getgid_t)(void);
typedef int (__sys_getlogin_t)(char * __kerncap, u_int);
typedef int (__sys_setlogin_t)(const char * __kerncap);
typedef int (__sys_acct_t)(const char * __kerncap);
typedef int (__sys_sigaltstack_t)(const struct sigaltstack * __kerncap, struct sigaltstack * __kerncap);
typedef int (__sys_ioctl_t)(int, u_long, char * __kerncap);
typedef int (__sys_reboot_t)(int);
typedef int (__sys_revoke_t)(const char * __kerncap);
typedef int (__sys_symlink_t)(const char * __kerncap, const char * __kerncap);
typedef ssize_t (__sys_readlink_t)(const char * __kerncap, char * __kerncap, size_t);
typedef int (__sys_execve_t)(const char * __kerncap, char * __kerncap * __kerncap, char * __kerncap * __kerncap);
typedef mode_t (__sys_umask_t)(mode_t);
typedef int (__sys_chroot_t)(const char * __kerncap);
typedef int (__sys_msync_t)(void * __kerncap, size_t, int);
typedef int (__sys_vfork_t)(void);
typedef int (__sys_munmap_t)(void * __kerncap, size_t);
typedef int (__sys_mprotect_t)(void * __kerncap, size_t, int);
typedef int (__sys_madvise_t)(void * __kerncap, size_t, int);
typedef int (__sys_mincore_t)(const void * __kerncap, size_t, char * __kerncap);
typedef int (__sys_getgroups_t)(int, gid_t * __kerncap);
typedef int (__sys_setgroups_t)(int, const gid_t * __kerncap);
typedef int (__sys_getpgrp_t)(void);
typedef int (__sys_setpgid_t)(int, int);
typedef int (__sys_setitimer_t)(int, const struct itimerval * __kerncap, struct itimerval * __kerncap);
typedef int (__sys_swapon_t)(const char * __kerncap);
typedef int (__sys_getitimer_t)(int, struct itimerval * __kerncap);
typedef int (__sys_getdtablesize_t)(void);
typedef int (__sys_dup2_t)(u_int, u_int);
typedef int (__sys_cheri_cidcap_alloc_t)(uintcap_t * __kerncap);
typedef int (__sys_fcntl_t)(int, int, intcap_t);
typedef int (__sys_select_t)(int, fd_set * __kerncap, fd_set * __kerncap, fd_set * __kerncap, struct timeval * __kerncap);
typedef int (__sys_fsync_t)(int);
typedef int (__sys_setpriority_t)(int, int, int);
typedef int (__sys_socket_t)(int, int, int);
typedef int (__sys_connect_t)(int, const struct sockaddr * __kerncap, __socklen_t);
typedef int (__sys_getpriority_t)(int, int);
typedef int (__sys_bind_t)(int, const struct sockaddr * __kerncap, __socklen_t);
typedef int (__sys_setsockopt_t)(int, int, int, const void * __kerncap, __socklen_t);
typedef int (__sys_listen_t)(int, int);
typedef int (__sys_gettimeofday_t)(struct timeval * __kerncap, struct timezone * __kerncap);
typedef int (__sys_getrusage_t)(int, struct rusage * __kerncap);
typedef int (__sys_getsockopt_t)(int, int, int, void * __kerncap, __socklen_t * __kerncap);
typedef int (__sys_readv_t)(int, const struct iovec * __kerncap, u_int);
typedef int (__sys_writev_t)(int, const struct iovec * __kerncap, u_int);
typedef int (__sys_settimeofday_t)(const struct timeval * __kerncap, const struct timezone * __kerncap);
typedef int (__sys_fchown_t)(int, int, int);
typedef int (__sys_fchmod_t)(int, mode_t);
typedef int (__sys_setreuid_t)(int, int);
typedef int (__sys_setregid_t)(int, int);
typedef int (__sys_rename_t)(const char * __kerncap, const char * __kerncap);
typedef int (__sys_flock_t)(int, int);
typedef int (__sys_mkfifo_t)(const char * __kerncap, mode_t);
typedef ssize_t (__sys_sendto_t)(int, const void * __kerncap, size_t, int, const struct sockaddr * __kerncap, __socklen_t);
typedef int (__sys_shutdown_t)(int, int);
typedef int (__sys_socketpair_t)(int, int, int, int * __kerncap);
typedef int (__sys_mkdir_t)(const char * __kerncap, mode_t);
typedef int (__sys_rmdir_t)(const char * __kerncap);
typedef int (__sys_utimes_t)(const char * __kerncap, const struct timeval * __kerncap);
typedef int (__sys_adjtime_t)(const struct timeval * __kerncap, struct timeval * __kerncap);
typedef int (__sys_setsid_t)(void);
typedef int (__sys_quotactl_t)(const char * __kerncap, int, int, void * __kerncap);
typedef int (__sys_nlm_syscall_t)(int, int, int, char * __kerncap * __kerncap);
typedef int (__sys_nfssvc_t)(int, void * __kerncap);
typedef int (__sys_lgetfh_t)(const char * __kerncap, struct fhandle * __kerncap);
typedef int (__sys_getfh_t)(const char * __kerncap, struct fhandle * __kerncap);
typedef int (__sys_sysarch_t)(int, char * __kerncap);
typedef int (__sys_rtprio_t)(int, pid_t, struct rtprio * __kerncap);
typedef int (__sys_semsys_t)(int, intcap_t, intcap_t, intcap_t, intcap_t);
typedef int (__sys_msgsys_t)(int, intcap_t, intcap_t, intcap_t, intcap_t, intcap_t);
typedef int (__sys_shmsys_t)(int, intcap_t, intcap_t, intcap_t);
typedef int (__sys_setfib_t)(int);
typedef int (__sys_ntp_adjtime_t)(struct timex * __kerncap);
typedef int (__sys_setgid_t)(gid_t);
typedef int (__sys_setegid_t)(gid_t);
typedef int (__sys_seteuid_t)(uid_t);
typedef int (__sys_pathconf_t)(const char * __kerncap, int);
typedef int (__sys_fpathconf_t)(int, int);
typedef int (__sys_getrlimit_t)(u_int, struct rlimit * __kerncap);
typedef int (__sys_setrlimit_t)(u_int, struct rlimit * __kerncap);
typedef int (__sys___sysctl_t)(int * __kerncap, u_int, void * __kerncap, size_t * __kerncap, const void * __kerncap, size_t);
typedef int (__sys_mlock_t)(const void * __kerncap, size_t);
typedef int (__sys_munlock_t)(const void * __kerncap, size_t);
typedef int (__sys_undelete_t)(const char * __kerncap);
typedef int (__sys_futimes_t)(int, const struct timeval * __kerncap);
typedef int (__sys_getpgid_t)(pid_t);
typedef int (__sys_poll_t)(struct pollfd * __kerncap, u_int, int);
typedef int (__sys_semget_t)(key_t, int, int);
typedef int (__sys_semop_t)(int, struct sembuf * __kerncap, size_t);
typedef int (__sys_msgget_t)(key_t, int);
typedef int (__sys_msgsnd_t)(int, const void * __kerncap, size_t, int);
typedef ssize_t (__sys_msgrcv_t)(int, void * __kerncap, size_t, long, int);
typedef void * (__sys_shmat_t)(int, const void * __kerncap, int);
typedef int (__sys_shmdt_t)(const void * __kerncap);
typedef int (__sys_shmget_t)(key_t, size_t, int);
typedef int (__sys_clock_gettime_t)(clockid_t, struct timespec * __kerncap);
typedef int (__sys_clock_settime_t)(clockid_t, const struct timespec * __kerncap);
typedef int (__sys_clock_getres_t)(clockid_t, struct timespec * __kerncap);
typedef int (__sys_ktimer_create_t)(clockid_t, struct sigevent * __kerncap, int * __kerncap);
typedef int (__sys_ktimer_delete_t)(int);
typedef int (__sys_ktimer_settime_t)(int, int, const struct itimerspec * __kerncap, struct itimerspec * __kerncap);
typedef int (__sys_ktimer_gettime_t)(int, struct itimerspec * __kerncap);
typedef int (__sys_ktimer_getoverrun_t)(int);
typedef int (__sys_nanosleep_t)(const struct timespec * __kerncap, struct timespec * __kerncap);
typedef int (__sys_ffclock_getcounter_t)(ffcounter * __kerncap);
typedef int (__sys_ffclock_setestimate_t)(struct ffclock_estimate * __kerncap);
typedef int (__sys_ffclock_getestimate_t)(struct ffclock_estimate * __kerncap);
typedef int (__sys_clock_nanosleep_t)(clockid_t, int, const struct timespec * __kerncap, struct timespec * __kerncap);
typedef int (__sys_clock_getcpuclockid2_t)(id_t, int, clockid_t * __kerncap);
typedef int (__sys_ntp_gettime_t)(struct ntptimeval * __kerncap);
typedef int (__sys_minherit_t)(void * __kerncap, size_t, int);
typedef int (__sys_rfork_t)(int);
typedef int (__sys_issetugid_t)(void);
typedef int (__sys_lchown_t)(const char * __kerncap, int, int);
typedef int (__sys_aio_read_t)(struct aiocb * __kerncap);
typedef int (__sys_aio_write_t)(struct aiocb * __kerncap);
typedef int (__sys_lio_listio_t)(int, struct aiocb * __kerncap const * __kerncap, int, struct sigevent * __kerncap);
typedef int (__sys_kbounce_t)(const void * __kerncap, void * __kerncap, size_t, int);
typedef int (__sys_flag_captured_t)(const char * __kerncap, uint32_t);
typedef int (__sys_cheri_revoke_get_shadow_t)(int, void * __kerncap, void * __kerncap);
typedef void * (__sys_cheri_revoke_t)(int, uint64_t, struct cheri_revoke_syscall_info * __kerncap);
typedef int (__sys_lchmod_t)(const char * __kerncap, mode_t);
typedef int (__sys_lutimes_t)(const char * __kerncap, const struct timeval * __kerncap);
typedef ssize_t (__sys_preadv_t)(int, struct iovec * __kerncap, u_int, off_t);
typedef ssize_t (__sys_pwritev_t)(int, struct iovec * __kerncap, u_int, off_t);
typedef int (__sys_fhopen_t)(const struct fhandle * __kerncap, int);
typedef int (__sys_modnext_t)(int);
typedef int (__sys_modstat_t)(int, struct module_stat * __kerncap);
typedef int (__sys_modfnext_t)(int);
typedef int (__sys_modfind_t)(const char * __kerncap);
typedef int (__sys_kldload_t)(const char * __kerncap);
typedef int (__sys_kldunload_t)(int);
typedef int (__sys_kldfind_t)(const char * __kerncap);
typedef int (__sys_kldnext_t)(int);
typedef int (__sys_kldstat_t)(int, struct kld_file_stat * __kerncap);
typedef int (__sys_kldfirstmod_t)(int);
typedef int (__sys_getsid_t)(pid_t);
typedef int (__sys_setresuid_t)(uid_t, uid_t, uid_t);
typedef int (__sys_setresgid_t)(gid_t, gid_t, gid_t);
typedef ssize_t (__sys_aio_return_t)(struct aiocb * __kerncap);
typedef int (__sys_aio_suspend_t)(const struct aiocb * __kerncap const * __kerncap, int, const struct timespec * __kerncap);
typedef int (__sys_aio_cancel_t)(int, struct aiocb * __kerncap);
typedef int (__sys_aio_error_t)(struct aiocb * __kerncap);
typedef int (__sys_mlockall_t)(int);
typedef int (__sys_munlockall_t)(void);
typedef int (__sys___getcwd_t)(char * __kerncap, size_t);
typedef int (__sys_sched_setparam_t)(pid_t, const struct sched_param * __kerncap);
typedef int (__sys_sched_getparam_t)(pid_t, struct sched_param * __kerncap);
typedef int (__sys_sched_setscheduler_t)(pid_t, int, const struct sched_param * __kerncap);
typedef int (__sys_sched_getscheduler_t)(pid_t);
typedef int (__sys_sched_yield_t)(void);
typedef int (__sys_sched_get_priority_max_t)(int);
typedef int (__sys_sched_get_priority_min_t)(int);
typedef int (__sys_sched_rr_get_interval_t)(pid_t, struct timespec * __kerncap);
typedef int (__sys_utrace_t)(const void * __kerncap, size_t);
typedef int (__sys_kldsym_t)(int, int, void * __kerncap);
typedef int (__sys_jail_t)(struct jail * __kerncap);
typedef int (__sys_nnpfs_syscall_t)(int, char * __kerncap, int, void * __kerncap, int);
typedef int (__sys_sigprocmask_t)(int, const sigset_t * __kerncap, sigset_t * __kerncap);
typedef int (__sys_sigsuspend_t)(const sigset_t * __kerncap);
typedef int (__sys_sigpending_t)(sigset_t * __kerncap);
typedef int (__sys_sigtimedwait_t)(const sigset_t * __kerncap, struct __siginfo * __kerncap, const struct timespec * __kerncap);
typedef int (__sys_sigwaitinfo_t)(const sigset_t * __kerncap, struct __siginfo * __kerncap);
typedef int (__sys___acl_get_file_t)(const char * __kerncap, __acl_type_t, struct acl * __kerncap);
typedef int (__sys___acl_set_file_t)(const char * __kerncap, __acl_type_t, struct acl * __kerncap);
typedef int (__sys___acl_get_fd_t)(int, __acl_type_t, struct acl * __kerncap);
typedef int (__sys___acl_set_fd_t)(int, __acl_type_t, struct acl * __kerncap);
typedef int (__sys___acl_delete_file_t)(const char * __kerncap, __acl_type_t);
typedef int (__sys___acl_delete_fd_t)(int, __acl_type_t);
typedef int (__sys___acl_aclcheck_file_t)(const char * __kerncap, __acl_type_t, struct acl * __kerncap);
typedef int (__sys___acl_aclcheck_fd_t)(int, __acl_type_t, struct acl * __kerncap);
typedef int (__sys_extattrctl_t)(const char * __kerncap, int, const char * __kerncap, int, const char * __kerncap);
typedef ssize_t (__sys_extattr_set_file_t)(const char * __kerncap, int, const char * __kerncap, void * __kerncap, size_t);
typedef ssize_t (__sys_extattr_get_file_t)(const char * __kerncap, int, const char * __kerncap, void * __kerncap, size_t);
typedef int (__sys_extattr_delete_file_t)(const char * __kerncap, int, const char * __kerncap);
typedef ssize_t (__sys_aio_waitcomplete_t)(struct aiocb * __kerncap * __kerncap, struct timespec * __kerncap);
typedef int (__sys_getresuid_t)(uid_t * __kerncap, uid_t * __kerncap, uid_t * __kerncap);
typedef int (__sys_getresgid_t)(gid_t * __kerncap, gid_t * __kerncap, gid_t * __kerncap);
typedef int (__sys_kqueue_t)(void);
typedef ssize_t (__sys_extattr_set_fd_t)(int, int, const char * __kerncap, void * __kerncap, size_t);
typedef ssize_t (__sys_extattr_get_fd_t)(int, int, const char * __kerncap, void * __kerncap, size_t);
typedef int (__sys_extattr_delete_fd_t)(int, int, const char * __kerncap);
typedef int (__sys___setugid_t)(int);
typedef int (__sys_eaccess_t)(const char * __kerncap, int);
typedef int (__sys_afs3_syscall_t)(long, long, long, long, long, long, long);
typedef int (__sys_nmount_t)(struct iovec * __kerncap, unsigned int, int);
typedef int (__sys___mac_get_proc_t)(struct mac * __kerncap);
typedef int (__sys___mac_set_proc_t)(struct mac * __kerncap);
typedef int (__sys___mac_get_fd_t)(int, struct mac * __kerncap);
typedef int (__sys___mac_get_file_t)(const char * __kerncap, struct mac * __kerncap);
typedef int (__sys___mac_set_fd_t)(int, struct mac * __kerncap);
typedef int (__sys___mac_set_file_t)(const char * __kerncap, struct mac * __kerncap);
typedef int (__sys_kenv_t)(int, const char * __kerncap, char * __kerncap, int);
typedef int (__sys_lchflags_t)(const char * __kerncap, u_long);
typedef int (__sys_uuidgen_t)(struct uuid * __kerncap, int);
typedef int (__sys_sendfile_t)(int, int, off_t, size_t, struct sf_hdtr * __kerncap, off_t * __kerncap, int);
typedef int (__sys_mac_syscall_t)(const char * __kerncap, int, void * __kerncap);
typedef int (__sys_ksem_close_t)(semid_t);
typedef int (__sys_ksem_post_t)(semid_t);
typedef int (__sys_ksem_wait_t)(semid_t);
typedef int (__sys_ksem_trywait_t)(semid_t);
typedef int (__sys_ksem_init_t)(semid_t * __kerncap, unsigned int);
typedef int (__sys_ksem_open_t)(semid_t * __kerncap, const char * __kerncap, int, mode_t, unsigned int);
typedef int (__sys_ksem_unlink_t)(const char * __kerncap);
typedef int (__sys_ksem_getvalue_t)(semid_t, int * __kerncap);
typedef int (__sys_ksem_destroy_t)(semid_t);
typedef int (__sys___mac_get_pid_t)(pid_t, struct mac * __kerncap);
typedef int (__sys___mac_get_link_t)(const char * __kerncap, struct mac * __kerncap);
typedef int (__sys___mac_set_link_t)(const char * __kerncap, struct mac * __kerncap);
typedef ssize_t (__sys_extattr_set_link_t)(const char * __kerncap, int, const char * __kerncap, void * __kerncap, size_t);
typedef ssize_t (__sys_extattr_get_link_t)(const char * __kerncap, int, const char * __kerncap, void * __kerncap, size_t);
typedef int (__sys_extattr_delete_link_t)(const char * __kerncap, int, const char * __kerncap);
typedef int (__sys___mac_execve_t)(const char * __kerncap, char * __kerncap * __kerncap, char * __kerncap * __kerncap, struct mac * __kerncap);
typedef int (__sys_sigaction_t)(int, const struct sigaction * __kerncap, struct sigaction * __kerncap);
typedef int (__sys_sigreturn_t)(const struct __ucontext * __kerncap);
typedef int (__sys_getcontext_t)(struct __ucontext * __kerncap);
typedef int (__sys_setcontext_t)(const struct __ucontext * __kerncap);
typedef int (__sys_swapcontext_t)(struct __ucontext * __kerncap, const struct __ucontext * __kerncap);
typedef int (__sys___acl_get_link_t)(const char * __kerncap, __acl_type_t, struct acl * __kerncap);
typedef int (__sys___acl_set_link_t)(const char * __kerncap, __acl_type_t, struct acl * __kerncap);
typedef int (__sys___acl_delete_link_t)(const char * __kerncap, __acl_type_t);
typedef int (__sys___acl_aclcheck_link_t)(const char * __kerncap, __acl_type_t, struct acl * __kerncap);
typedef int (__sys_sigwait_t)(const sigset_t * __kerncap, int * __kerncap);
typedef int (__sys_thr_create_t)(struct __ucontext * __kerncap, long * __kerncap, int);
typedef void (__sys_thr_exit_t)(long * __kerncap);
typedef int (__sys_thr_self_t)(long * __kerncap);
typedef int (__sys_thr_kill_t)(long, int);
typedef int (__sys_jail_attach_t)(int);
typedef ssize_t (__sys_extattr_list_fd_t)(int, int, void * __kerncap, size_t);
typedef ssize_t (__sys_extattr_list_file_t)(const char * __kerncap, int, void * __kerncap, size_t);
typedef ssize_t (__sys_extattr_list_link_t)(const char * __kerncap, int, void * __kerncap, size_t);
typedef int (__sys_ksem_timedwait_t)(semid_t, const struct timespec * __kerncap);
typedef int (__sys_thr_suspend_t)(const struct timespec * __kerncap);
typedef int (__sys_thr_wake_t)(long);
typedef int (__sys_kldunloadf_t)(int, int);
typedef int (__sys_audit_t)(const void * __kerncap, u_int);
typedef int (__sys_auditon_t)(int, void * __kerncap, u_int);
typedef int (__sys_getauid_t)(uid_t * __kerncap);
typedef int (__sys_setauid_t)(uid_t * __kerncap);
typedef int (__sys_getaudit_t)(struct auditinfo * __kerncap);
typedef int (__sys_setaudit_t)(struct auditinfo * __kerncap);
typedef int (__sys_getaudit_addr_t)(struct auditinfo_addr * __kerncap, u_int);
typedef int (__sys_setaudit_addr_t)(struct auditinfo_addr * __kerncap, u_int);
typedef int (__sys_auditctl_t)(const char * __kerncap);
typedef int (__sys__umtx_op_t)(void * __kerncap, int, u_long, void * __kerncap, void * __kerncap);
typedef int (__sys_thr_new_t)(struct thr_param * __kerncap, int);
typedef int (__sys_sigqueue_t)(pid_t, int, void * __kerncap);
typedef int (__sys_kmq_open_t)(const char * __kerncap, int, mode_t, const struct mq_attr * __kerncap);
typedef int (__sys_kmq_setattr_t)(int, const struct mq_attr * __kerncap, struct mq_attr * __kerncap);
typedef int (__sys_kmq_timedreceive_t)(int, char * __kerncap, size_t, unsigned * __kerncap, const struct timespec * __kerncap);
typedef int (__sys_kmq_timedsend_t)(int, const char * __kerncap, size_t, unsigned, const struct timespec * __kerncap);
typedef int (__sys_kmq_notify_t)(int, const struct sigevent * __kerncap);
typedef int (__sys_kmq_unlink_t)(const char * __kerncap);
typedef void (__sys_abort2_t)(const char * __kerncap, int, void * __kerncap * __kerncap);
typedef int (__sys_thr_set_name_t)(long, const char * __kerncap);
typedef int (__sys_aio_fsync_t)(int, struct aiocb * __kerncap);
typedef int (__sys_rtprio_thread_t)(int, lwpid_t, struct rtprio * __kerncap);
typedef int (__sys_sctp_peeloff_t)(int, uint32_t);
typedef int (__sys_sctp_generic_sendmsg_t)(int, void * __kerncap, int, const struct sockaddr * __kerncap, __socklen_t, struct sctp_sndrcvinfo * __kerncap, int);
typedef int (__sys_sctp_generic_sendmsg_iov_t)(int, struct iovec * __kerncap, int, const struct sockaddr * __kerncap, __socklen_t, struct sctp_sndrcvinfo * __kerncap, int);
typedef int (__sys_sctp_generic_recvmsg_t)(int, struct iovec * __kerncap, int, struct sockaddr * __kerncap, __socklen_t * __kerncap, struct sctp_sndrcvinfo * __kerncap, int * __kerncap);
typedef ssize_t (__sys_pread_t)(int, void * __kerncap, size_t, off_t);
typedef ssize_t (__sys_pwrite_t)(int, const void * __kerncap, size_t, off_t);
typedef void * (__sys_mmap_t)(void * __kerncap, size_t, int, int, int, off_t);
typedef off_t (__sys_lseek_t)(int, off_t, int);
typedef int (__sys_truncate_t)(const char * __kerncap, off_t);
typedef int (__sys_ftruncate_t)(int, off_t);
typedef int (__sys_thr_kill2_t)(pid_t, long, int);
typedef int (__sys_shm_unlink_t)(const char * __kerncap);
typedef int (__sys_cpuset_t)(cpusetid_t * __kerncap);
typedef int (__sys_cpuset_setid_t)(cpuwhich_t, id_t, cpusetid_t);
typedef int (__sys_cpuset_getid_t)(cpulevel_t, cpuwhich_t, id_t, cpusetid_t * __kerncap);
typedef int (__sys_cpuset_getaffinity_t)(cpulevel_t, cpuwhich_t, id_t, size_t, cpuset_t * __kerncap);
typedef int (__sys_cpuset_setaffinity_t)(cpulevel_t, cpuwhich_t, id_t, size_t, const cpuset_t * __kerncap);
typedef int (__sys_faccessat_t)(int, const char * __kerncap, int, int);
typedef int (__sys_fchmodat_t)(int, const char * __kerncap, mode_t, int);
typedef int (__sys_fchownat_t)(int, const char * __kerncap, uid_t, gid_t, int);
typedef int (__sys_fexecve_t)(int, char * __kerncap * __kerncap, char * __kerncap * __kerncap);
typedef int (__sys_futimesat_t)(int, const char * __kerncap, const struct timeval * __kerncap);
typedef int (__sys_linkat_t)(int, const char * __kerncap, int, const char * __kerncap, int);
typedef int (__sys_mkdirat_t)(int, const char * __kerncap, mode_t);
typedef int (__sys_mkfifoat_t)(int, const char * __kerncap, mode_t);
typedef int (__sys_openat_t)(int, const char * __kerncap, int, mode_t);
typedef ssize_t (__sys_readlinkat_t)(int, const char * __kerncap, char * __kerncap, size_t);
typedef int (__sys_renameat_t)(int, const char * __kerncap, int, const char * __kerncap);
typedef int (__sys_symlinkat_t)(const char * __kerncap, int, const char * __kerncap);
typedef int (__sys_unlinkat_t)(int, const char * __kerncap, int);
typedef int (__sys_posix_openpt_t)(int);
typedef int (__sys_gssd_syscall_t)(const char * __kerncap);
typedef int (__sys_jail_get_t)(struct iovec * __kerncap, unsigned int, int);
typedef int (__sys_jail_set_t)(struct iovec * __kerncap, unsigned int, int);
typedef int (__sys_jail_remove_t)(int);
typedef int (__sys___semctl_t)(int, int, int, union semun * __kerncap);
typedef int (__sys_msgctl_t)(int, int, struct msqid_ds * __kerncap);
typedef int (__sys_shmctl_t)(int, int, struct shmid_ds * __kerncap);
typedef int (__sys_lpathconf_t)(const char * __kerncap, int);
typedef int (__sys___cap_rights_get_t)(int, int, cap_rights_t * __kerncap);
typedef int (__sys_cap_enter_t)(void);
typedef int (__sys_cap_getmode_t)(u_int * __kerncap);
typedef int (__sys_pdfork_t)(int * __kerncap, int);
typedef int (__sys_pdkill_t)(int, int);
typedef int (__sys_pdgetpid_t)(int, pid_t * __kerncap);
typedef int (__sys_pselect_t)(int, fd_set * __kerncap, fd_set * __kerncap, fd_set * __kerncap, const struct timespec * __kerncap, const sigset_t * __kerncap);
typedef int (__sys_getloginclass_t)(char * __kerncap, size_t);
typedef int (__sys_setloginclass_t)(const char * __kerncap);
typedef int (__sys_rctl_get_racct_t)(const void * __kerncap, size_t, void * __kerncap, size_t);
typedef int (__sys_rctl_get_rules_t)(const void * __kerncap, size_t, void * __kerncap, size_t);
typedef int (__sys_rctl_get_limits_t)(const void * __kerncap, size_t, void * __kerncap, size_t);
typedef int (__sys_rctl_add_rule_t)(const void * __kerncap, size_t, void * __kerncap, size_t);
typedef int (__sys_rctl_remove_rule_t)(const void * __kerncap, size_t, void * __kerncap, size_t);
typedef int (__sys_posix_fallocate_t)(int, off_t, off_t);
typedef int (__sys_posix_fadvise_t)(int, off_t, off_t, int);
typedef int (__sys_wait6_t)(idtype_t, id_t, int * __kerncap, int, struct __wrusage * __kerncap, struct __siginfo * __kerncap);
typedef int (__sys_cap_rights_limit_t)(int, cap_rights_t * __kerncap);
typedef int (__sys_cap_ioctls_limit_t)(int, const u_long * __kerncap, size_t);
typedef ssize_t (__sys_cap_ioctls_get_t)(int, u_long * __kerncap, size_t);
typedef int (__sys_cap_fcntls_limit_t)(int, uint32_t);
typedef int (__sys_cap_fcntls_get_t)(int, uint32_t * __kerncap);
typedef int (__sys_bindat_t)(int, int, const struct sockaddr * __kerncap, __socklen_t);
typedef int (__sys_connectat_t)(int, int, const struct sockaddr * __kerncap, __socklen_t);
typedef int (__sys_chflagsat_t)(int, const char * __kerncap, u_long, int);
typedef int (__sys_accept4_t)(int, struct sockaddr * __kerncap, __socklen_t * __kerncap, int);
typedef int (__sys_pipe2_t)(int * __kerncap, int);
typedef int (__sys_aio_mlock_t)(struct aiocb * __kerncap);
typedef int (__sys_procctl_t)(idtype_t, id_t, int, void * __kerncap);
typedef int (__sys_ppoll_t)(struct pollfd * __kerncap, u_int, const struct timespec * __kerncap, const sigset_t * __kerncap);
typedef int (__sys_futimens_t)(int, const struct timespec * __kerncap);
typedef int (__sys_utimensat_t)(int, const char * __kerncap, const struct timespec * __kerncap, int);
typedef int (__sys_fdatasync_t)(int);
typedef int (__sys_fstat_t)(int, struct stat * __kerncap);
typedef int (__sys_fstatat_t)(int, const char * __kerncap, struct stat * __kerncap, int);
typedef int (__sys_fhstat_t)(const struct fhandle * __kerncap, struct stat * __kerncap);
typedef ssize_t (__sys_getdirentries_t)(int, char * __kerncap, size_t, off_t * __kerncap);
typedef int (__sys_statfs_t)(const char * __kerncap, struct statfs * __kerncap);
typedef int (__sys_fstatfs_t)(int, struct statfs * __kerncap);
typedef int (__sys_getfsstat_t)(struct statfs * __kerncap, long, int);
typedef int (__sys_fhstatfs_t)(const struct fhandle * __kerncap, struct statfs * __kerncap);
typedef int (__sys_mknodat_t)(int, const char * __kerncap, mode_t, dev_t);
typedef int (__sys_kevent_t)(int, const struct kevent * __kerncap, int, struct kevent * __kerncap, int, const struct timespec * __kerncap);
typedef int (__sys_cpuset_getdomain_t)(cpulevel_t, cpuwhich_t, id_t, size_t, domainset_t * __kerncap, int * __kerncap);
typedef int (__sys_cpuset_setdomain_t)(cpulevel_t, cpuwhich_t, id_t, size_t, domainset_t * __kerncap, int);
typedef int (__sys_getrandom_t)(void * __kerncap, size_t, unsigned int);
typedef int (__sys_getfhat_t)(int, char * __kerncap, struct fhandle * __kerncap, int);
typedef int (__sys_fhlink_t)(struct fhandle * __kerncap, const char * __kerncap);
typedef int (__sys_fhlinkat_t)(struct fhandle * __kerncap, int, const char * __kerncap);
typedef int (__sys_fhreadlink_t)(struct fhandle * __kerncap, char * __kerncap, size_t);
typedef int (__sys_funlinkat_t)(int, const char * __kerncap, int, int);
typedef ssize_t (__sys_copy_file_range_t)(int, off_t * __kerncap, int, off_t * __kerncap, size_t, unsigned int);
typedef int (__sys___sysctlbyname_t)(const char * __kerncap, size_t, void * __kerncap, size_t * __kerncap, void * __kerncap, size_t);
typedef int (__sys_shm_open2_t)(const char * __kerncap, int, mode_t, int, const char * __kerncap);
typedef int (__sys_shm_rename_t)(const char * __kerncap, const char * __kerncap, int);
typedef int (__sys_sigfastblock_t)(int, void * __kerncap);
typedef int (__sys___realpathat_t)(int, const char * __kerncap, char * __kerncap, size_t, int);
typedef int (__sys_close_range_t)(u_int, u_int, int);
typedef int (__sys_rpctls_syscall_t)(int, const char * __kerncap);
typedef int (__sys___specialfd_t)(int, const void * __kerncap, size_t);
typedef int (__sys_aio_writev_t)(struct aiocb * __kerncap);
typedef int (__sys_aio_readv_t)(struct aiocb * __kerncap);
typedef int (__sys_fspacectl_t)(int, int, const struct spacectl_range * __kerncap, int, struct spacectl_range * __kerncap);
typedef int (__sys_sched_getcpu_t)(void);
typedef int (__sys_swapoff_t)(const char * __kerncap, u_int);
typedef int (__sys_kqueuex_t)(u_int);
typedef int (__sys_membarrier_t)(int, unsigned, int);
typedef int (__sys_timerfd_create_t)(int, int);
typedef int (__sys_timerfd_gettime_t)(int, struct itimerspec * __kerncap);
typedef int (__sys_timerfd_settime_t)(int, int, const struct itimerspec * __kerncap, struct itimerspec * __kerncap);

void __sys_exit(int rval);
int __sys_fork(void);
ssize_t __sys_read(int fd, void * __kerncap buf, size_t nbyte);
ssize_t __sys_write(int fd, const void * __kerncap buf, size_t nbyte);
int __sys_open(const char * __kerncap path, int flags, mode_t mode);
int __sys_close(int fd);
int __sys_wait4(int pid, int * __kerncap status, int options, struct rusage * __kerncap rusage);
int __sys_link(const char * __kerncap path, const char * __kerncap to);
int __sys_unlink(const char * __kerncap path);
int __sys_chdir(const char * __kerncap path);
int __sys_fchdir(int fd);
int __sys_chmod(const char * __kerncap path, mode_t mode);
int __sys_chown(const char * __kerncap path, int uid, int gid);
void * __sys_break(char * __kerncap nsize);
pid_t __sys_getpid(void);
int __sys_mount(const char * __kerncap type, const char * __kerncap path, int flags, void * __kerncap data);
int __sys_unmount(const char * __kerncap path, int flags);
int __sys_setuid(uid_t uid);
uid_t __sys_getuid(void);
uid_t __sys_geteuid(void);
int __sys_ptrace(int req, pid_t pid, char * __kerncap addr, int data);
ssize_t __sys_recvmsg(int s, struct msghdr * __kerncap msg, int flags);
ssize_t __sys_sendmsg(int s, const struct msghdr * __kerncap msg, int flags);
ssize_t __sys_recvfrom(int s, void * __kerncap buf, size_t len, int flags, struct sockaddr * __kerncap from, __socklen_t * __kerncap fromlenaddr);
int __sys_accept(int s, struct sockaddr * __kerncap name, __socklen_t * __kerncap anamelen);
int __sys_getpeername(int fdes, struct sockaddr * __kerncap asa, __socklen_t * __kerncap alen);
int __sys_getsockname(int fdes, struct sockaddr * __kerncap asa, __socklen_t * __kerncap alen);
int __sys_access(const char * __kerncap path, int amode);
int __sys_chflags(const char * __kerncap path, u_long flags);
int __sys_fchflags(int fd, u_long flags);
int __sys_sync(void);
int __sys_kill(int pid, int signum);
pid_t __sys_getppid(void);
int __sys_dup(u_int fd);
gid_t __sys_getegid(void);
int __sys_profil(char * __kerncap samples, size_t size, size_t offset, u_int scale);
int __sys_ktrace(const char * __kerncap fname, int ops, int facs, int pid);
gid_t __sys_getgid(void);
int __sys_getlogin(char * __kerncap namebuf, u_int namelen);
int __sys_setlogin(const char * __kerncap namebuf);
int __sys_acct(const char * __kerncap path);
int __sys_sigaltstack(const struct sigaltstack * __kerncap ss, struct sigaltstack * __kerncap oss);
int __sys_ioctl(int fd, u_long com, char * __kerncap data);
int __sys_reboot(int opt);
int __sys_revoke(const char * __kerncap path);
int __sys_symlink(const char * __kerncap path, const char * __kerncap link);
ssize_t __sys_readlink(const char * __kerncap path, char * __kerncap buf, size_t count);
int __sys_execve(const char * __kerncap fname, char * __kerncap * __kerncap argv, char * __kerncap * __kerncap envv);
mode_t __sys_umask(mode_t newmask);
int __sys_chroot(const char * __kerncap path);
int __sys_msync(void * __kerncap addr, size_t len, int flags);
int __sys_vfork(void);
int __sys_munmap(void * __kerncap addr, size_t len);
int __sys_mprotect(void * __kerncap addr, size_t len, int prot);
int __sys_madvise(void * __kerncap addr, size_t len, int behav);
int __sys_mincore(const void * __kerncap addr, size_t len, char * __kerncap vec);
int __sys_getgroups(int gidsetsize, gid_t * __kerncap gidset);
int __sys_setgroups(int gidsetsize, const gid_t * __kerncap gidset);
int __sys_getpgrp(void);
int __sys_setpgid(int pid, int pgid);
int __sys_setitimer(int which, const struct itimerval * __kerncap itv, struct itimerval * __kerncap oitv);
int __sys_swapon(const char * __kerncap name);
int __sys_getitimer(int which, struct itimerval * __kerncap itv);
int __sys_getdtablesize(void);
int __sys_dup2(u_int from, u_int to);
int __sys_cheri_cidcap_alloc(uintcap_t * __kerncap cidp);
int __sys_fcntl(int fd, int cmd, intcap_t arg);
int __sys_select(int nd, fd_set * __kerncap in, fd_set * __kerncap ou, fd_set * __kerncap ex, struct timeval * __kerncap tv);
int __sys_fsync(int fd);
int __sys_setpriority(int which, int who, int prio);
int __sys_socket(int domain, int type, int protocol);
int __sys_connect(int s, const struct sockaddr * __kerncap name, __socklen_t namelen);
int __sys_getpriority(int which, int who);
int __sys_bind(int s, const struct sockaddr * __kerncap name, __socklen_t namelen);
int __sys_setsockopt(int s, int level, int name, const void * __kerncap val, __socklen_t valsize);
int __sys_listen(int s, int backlog);
int __sys_gettimeofday(struct timeval * __kerncap tp, struct timezone * __kerncap tzp);
int __sys_getrusage(int who, struct rusage * __kerncap rusage);
int __sys_getsockopt(int s, int level, int name, void * __kerncap val, __socklen_t * __kerncap avalsize);
int __sys_readv(int fd, const struct iovec * __kerncap iovp, u_int iovcnt);
int __sys_writev(int fd, const struct iovec * __kerncap iovp, u_int iovcnt);
int __sys_settimeofday(const struct timeval * __kerncap tv, const struct timezone * __kerncap tzp);
int __sys_fchown(int fd, int uid, int gid);
int __sys_fchmod(int fd, mode_t mode);
int __sys_setreuid(int ruid, int euid);
int __sys_setregid(int rgid, int egid);
int __sys_rename(const char * __kerncap from, const char * __kerncap to);
int __sys_flock(int fd, int how);
int __sys_mkfifo(const char * __kerncap path, mode_t mode);
ssize_t __sys_sendto(int s, const void * __kerncap buf, size_t len, int flags, const struct sockaddr * __kerncap to, __socklen_t tolen);
int __sys_shutdown(int s, int how);
int __sys_socketpair(int domain, int type, int protocol, int * __kerncap rsv);
int __sys_mkdir(const char * __kerncap path, mode_t mode);
int __sys_rmdir(const char * __kerncap path);
int __sys_utimes(const char * __kerncap path, const struct timeval * __kerncap tptr);
int __sys_adjtime(const struct timeval * __kerncap delta, struct timeval * __kerncap olddelta);
int __sys_setsid(void);
int __sys_quotactl(const char * __kerncap path, int cmd, int uid, void * __kerncap arg);
int __sys_nlm_syscall(int debug_level, int grace_period, int addr_count, char * __kerncap * __kerncap addrs);
int __sys_nfssvc(int flag, void * __kerncap argp);
int __sys_lgetfh(const char * __kerncap fname, struct fhandle * __kerncap fhp);
int __sys_getfh(const char * __kerncap fname, struct fhandle * __kerncap fhp);
int __sys_sysarch(int op, char * __kerncap parms);
int __sys_rtprio(int function, pid_t pid, struct rtprio * __kerncap rtp);
int __sys_semsys(int which, intcap_t a2, intcap_t a3, intcap_t a4, intcap_t a5);
int __sys_msgsys(int which, intcap_t a2, intcap_t a3, intcap_t a4, intcap_t a5, intcap_t a6);
int __sys_shmsys(int which, intcap_t a2, intcap_t a3, intcap_t a4);
int __sys_setfib(int fibnum);
int __sys_ntp_adjtime(struct timex * __kerncap tp);
int __sys_setgid(gid_t gid);
int __sys_setegid(gid_t egid);
int __sys_seteuid(uid_t euid);
int __sys_pathconf(const char * __kerncap path, int name);
int __sys_fpathconf(int fd, int name);
int __sys_getrlimit(u_int which, struct rlimit * __kerncap rlp);
int __sys_setrlimit(u_int which, struct rlimit * __kerncap rlp);
int __sys___sysctl(int * __kerncap name, u_int namelen, void * __kerncap old, size_t * __kerncap oldlenp, const void * __kerncap new, size_t newlen);
int __sys_mlock(const void * __kerncap addr, size_t len);
int __sys_munlock(const void * __kerncap addr, size_t len);
int __sys_undelete(const char * __kerncap path);
int __sys_futimes(int fd, const struct timeval * __kerncap tptr);
int __sys_getpgid(pid_t pid);
int __sys_poll(struct pollfd * __kerncap fds, u_int nfds, int timeout);
int __sys_semget(key_t key, int nsems, int semflg);
int __sys_semop(int semid, struct sembuf * __kerncap sops, size_t nsops);
int __sys_msgget(key_t key, int msgflg);
int __sys_msgsnd(int msqid, const void * __kerncap msgp, size_t msgsz, int msgflg);
ssize_t __sys_msgrcv(int msqid, void * __kerncap msgp, size_t msgsz, long msgtyp, int msgflg);
void * __sys_shmat(int shmid, const void * __kerncap shmaddr, int shmflg);
int __sys_shmdt(const void * __kerncap shmaddr);
int __sys_shmget(key_t key, size_t size, int shmflg);
int __sys_clock_gettime(clockid_t clock_id, struct timespec * __kerncap tp);
int __sys_clock_settime(clockid_t clock_id, const struct timespec * __kerncap tp);
int __sys_clock_getres(clockid_t clock_id, struct timespec * __kerncap tp);
int __sys_ktimer_create(clockid_t clock_id, struct sigevent * __kerncap evp, int * __kerncap timerid);
int __sys_ktimer_delete(int timerid);
int __sys_ktimer_settime(int timerid, int flags, const struct itimerspec * __kerncap value, struct itimerspec * __kerncap ovalue);
int __sys_ktimer_gettime(int timerid, struct itimerspec * __kerncap value);
int __sys_ktimer_getoverrun(int timerid);
int __sys_nanosleep(const struct timespec * __kerncap rqtp, struct timespec * __kerncap rmtp);
int __sys_ffclock_getcounter(ffcounter * __kerncap ffcount);
int __sys_ffclock_setestimate(struct ffclock_estimate * __kerncap cest);
int __sys_ffclock_getestimate(struct ffclock_estimate * __kerncap cest);
int __sys_clock_nanosleep(clockid_t clock_id, int flags, const struct timespec * __kerncap rqtp, struct timespec * __kerncap rmtp);
int __sys_clock_getcpuclockid2(id_t id, int which, clockid_t * __kerncap clock_id);
int __sys_ntp_gettime(struct ntptimeval * __kerncap ntvp);
int __sys_minherit(void * __kerncap addr, size_t len, int inherit);
int __sys_rfork(int flags);
int __sys_issetugid(void);
int __sys_lchown(const char * __kerncap path, int uid, int gid);
int __sys_aio_read(struct aiocb * __kerncap aiocbp);
int __sys_aio_write(struct aiocb * __kerncap aiocbp);
int __sys_lio_listio(int mode, struct aiocb * __kerncap const * __kerncap acb_list, int nent, struct sigevent * __kerncap sig);
int __sys_kbounce(const void * __kerncap src, void * __kerncap dst, size_t len, int flags);
int __sys_flag_captured(const char * __kerncap message, uint32_t key);
int __sys_cheri_revoke_get_shadow(int flags, void * __kerncap arena, void * __kerncap shadow);
void * __sys_cheri_revoke(int flags, uint64_t start_epoch, struct cheri_revoke_syscall_info * __kerncap crsi);
int __sys_lchmod(const char * __kerncap path, mode_t mode);
int __sys_lutimes(const char * __kerncap path, const struct timeval * __kerncap tptr);
ssize_t __sys_preadv(int fd, struct iovec * __kerncap iovp, u_int iovcnt, off_t offset);
ssize_t __sys_pwritev(int fd, struct iovec * __kerncap iovp, u_int iovcnt, off_t offset);
int __sys_fhopen(const struct fhandle * __kerncap u_fhp, int flags);
int __sys_modnext(int modid);
int __sys_modstat(int modid, struct module_stat * __kerncap stat);
int __sys_modfnext(int modid);
int __sys_modfind(const char * __kerncap name);
int __sys_kldload(const char * __kerncap file);
int __sys_kldunload(int fileid);
int __sys_kldfind(const char * __kerncap file);
int __sys_kldnext(int fileid);
int __sys_kldstat(int fileid, struct kld_file_stat * __kerncap stat);
int __sys_kldfirstmod(int fileid);
int __sys_getsid(pid_t pid);
int __sys_setresuid(uid_t ruid, uid_t euid, uid_t suid);
int __sys_setresgid(gid_t rgid, gid_t egid, gid_t sgid);
ssize_t __sys_aio_return(struct aiocb * __kerncap aiocbp);
int __sys_aio_suspend(const struct aiocb * __kerncap const * __kerncap aiocbp, int nent, const struct timespec * __kerncap timeout);
int __sys_aio_cancel(int fd, struct aiocb * __kerncap aiocbp);
int __sys_aio_error(struct aiocb * __kerncap aiocbp);
int __sys_mlockall(int how);
int __sys_munlockall(void);
int __sys___getcwd(char * __kerncap buf, size_t buflen);
int __sys_sched_setparam(pid_t pid, const struct sched_param * __kerncap param);
int __sys_sched_getparam(pid_t pid, struct sched_param * __kerncap param);
int __sys_sched_setscheduler(pid_t pid, int policy, const struct sched_param * __kerncap param);
int __sys_sched_getscheduler(pid_t pid);
int __sys_sched_yield(void);
int __sys_sched_get_priority_max(int policy);
int __sys_sched_get_priority_min(int policy);
int __sys_sched_rr_get_interval(pid_t pid, struct timespec * __kerncap interval);
int __sys_utrace(const void * __kerncap addr, size_t len);
int __sys_kldsym(int fileid, int cmd, void * __kerncap data);
int __sys_jail(struct jail * __kerncap jailp);
int __sys_nnpfs_syscall(int operation, char * __kerncap a_pathP, int a_opcode, void * __kerncap a_paramsP, int a_followSymlinks);
int __sys_sigprocmask(int how, const sigset_t * __kerncap set, sigset_t * __kerncap oset);
int __sys_sigsuspend(const sigset_t * __kerncap sigmask);
int __sys_sigpending(sigset_t * __kerncap set);
int __sys_sigtimedwait(const sigset_t * __kerncap set, struct __siginfo * __kerncap info, const struct timespec * __kerncap timeout);
int __sys_sigwaitinfo(const sigset_t * __kerncap set, struct __siginfo * __kerncap info);
int __sys___acl_get_file(const char * __kerncap path, __acl_type_t type, struct acl * __kerncap aclp);
int __sys___acl_set_file(const char * __kerncap path, __acl_type_t type, struct acl * __kerncap aclp);
int __sys___acl_get_fd(int filedes, __acl_type_t type, struct acl * __kerncap aclp);
int __sys___acl_set_fd(int filedes, __acl_type_t type, struct acl * __kerncap aclp);
int __sys___acl_delete_file(const char * __kerncap path, __acl_type_t type);
int __sys___acl_delete_fd(int filedes, __acl_type_t type);
int __sys___acl_aclcheck_file(const char * __kerncap path, __acl_type_t type, struct acl * __kerncap aclp);
int __sys___acl_aclcheck_fd(int filedes, __acl_type_t type, struct acl * __kerncap aclp);
int __sys_extattrctl(const char * __kerncap path, int cmd, const char * __kerncap filename, int attrnamespace, const char * __kerncap attrname);
ssize_t __sys_extattr_set_file(const char * __kerncap path, int attrnamespace, const char * __kerncap attrname, void * __kerncap data, size_t nbytes);
ssize_t __sys_extattr_get_file(const char * __kerncap path, int attrnamespace, const char * __kerncap attrname, void * __kerncap data, size_t nbytes);
int __sys_extattr_delete_file(const char * __kerncap path, int attrnamespace, const char * __kerncap attrname);
ssize_t __sys_aio_waitcomplete(struct aiocb * __kerncap * __kerncap aiocbp, struct timespec * __kerncap timeout);
int __sys_getresuid(uid_t * __kerncap ruid, uid_t * __kerncap euid, uid_t * __kerncap suid);
int __sys_getresgid(gid_t * __kerncap rgid, gid_t * __kerncap egid, gid_t * __kerncap sgid);
int __sys_kqueue(void);
ssize_t __sys_extattr_set_fd(int fd, int attrnamespace, const char * __kerncap attrname, void * __kerncap data, size_t nbytes);
ssize_t __sys_extattr_get_fd(int fd, int attrnamespace, const char * __kerncap attrname, void * __kerncap data, size_t nbytes);
int __sys_extattr_delete_fd(int fd, int attrnamespace, const char * __kerncap attrname);
int __sys___setugid(int flag);
int __sys_eaccess(const char * __kerncap path, int amode);
int __sys_afs3_syscall(long syscall, long parm1, long parm2, long parm3, long parm4, long parm5, long parm6);
int __sys_nmount(struct iovec * __kerncap iovp, unsigned int iovcnt, int flags);
int __sys___mac_get_proc(struct mac * __kerncap mac_p);
int __sys___mac_set_proc(struct mac * __kerncap mac_p);
int __sys___mac_get_fd(int fd, struct mac * __kerncap mac_p);
int __sys___mac_get_file(const char * __kerncap path_p, struct mac * __kerncap mac_p);
int __sys___mac_set_fd(int fd, struct mac * __kerncap mac_p);
int __sys___mac_set_file(const char * __kerncap path_p, struct mac * __kerncap mac_p);
int __sys_kenv(int what, const char * __kerncap name, char * __kerncap value, int len);
int __sys_lchflags(const char * __kerncap path, u_long flags);
int __sys_uuidgen(struct uuid * __kerncap store, int count);
int __sys_sendfile(int fd, int s, off_t offset, size_t nbytes, struct sf_hdtr * __kerncap hdtr, off_t * __kerncap sbytes, int flags);
int __sys_mac_syscall(const char * __kerncap policy, int call, void * __kerncap arg);
int __sys_ksem_close(semid_t id);
int __sys_ksem_post(semid_t id);
int __sys_ksem_wait(semid_t id);
int __sys_ksem_trywait(semid_t id);
int __sys_ksem_init(semid_t * __kerncap idp, unsigned int value);
int __sys_ksem_open(semid_t * __kerncap idp, const char * __kerncap name, int oflag, mode_t mode, unsigned int value);
int __sys_ksem_unlink(const char * __kerncap name);
int __sys_ksem_getvalue(semid_t id, int * __kerncap val);
int __sys_ksem_destroy(semid_t id);
int __sys___mac_get_pid(pid_t pid, struct mac * __kerncap mac_p);
int __sys___mac_get_link(const char * __kerncap path_p, struct mac * __kerncap mac_p);
int __sys___mac_set_link(const char * __kerncap path_p, struct mac * __kerncap mac_p);
ssize_t __sys_extattr_set_link(const char * __kerncap path, int attrnamespace, const char * __kerncap attrname, void * __kerncap data, size_t nbytes);
ssize_t __sys_extattr_get_link(const char * __kerncap path, int attrnamespace, const char * __kerncap attrname, void * __kerncap data, size_t nbytes);
int __sys_extattr_delete_link(const char * __kerncap path, int attrnamespace, const char * __kerncap attrname);
int __sys___mac_execve(const char * __kerncap fname, char * __kerncap * __kerncap argv, char * __kerncap * __kerncap envv, struct mac * __kerncap mac_p);
int __sys_sigaction(int sig, const struct sigaction * __kerncap act, struct sigaction * __kerncap oact);
int __sys_sigreturn(const struct __ucontext * __kerncap sigcntxp);
int __sys_getcontext(struct __ucontext * __kerncap ucp);
int __sys_setcontext(const struct __ucontext * __kerncap ucp);
int __sys_swapcontext(struct __ucontext * __kerncap oucp, const struct __ucontext * __kerncap ucp);
int __sys___acl_get_link(const char * __kerncap path, __acl_type_t type, struct acl * __kerncap aclp);
int __sys___acl_set_link(const char * __kerncap path, __acl_type_t type, struct acl * __kerncap aclp);
int __sys___acl_delete_link(const char * __kerncap path, __acl_type_t type);
int __sys___acl_aclcheck_link(const char * __kerncap path, __acl_type_t type, struct acl * __kerncap aclp);
int __sys_sigwait(const sigset_t * __kerncap set, int * __kerncap sig);
int __sys_thr_create(struct __ucontext * __kerncap ctx, long * __kerncap id, int flags);
void __sys_thr_exit(long * __kerncap state);
int __sys_thr_self(long * __kerncap id);
int __sys_thr_kill(long id, int sig);
int __sys_jail_attach(int jid);
ssize_t __sys_extattr_list_fd(int fd, int attrnamespace, void * __kerncap data, size_t nbytes);
ssize_t __sys_extattr_list_file(const char * __kerncap path, int attrnamespace, void * __kerncap data, size_t nbytes);
ssize_t __sys_extattr_list_link(const char * __kerncap path, int attrnamespace, void * __kerncap data, size_t nbytes);
int __sys_ksem_timedwait(semid_t id, const struct timespec * __kerncap abstime);
int __sys_thr_suspend(const struct timespec * __kerncap timeout);
int __sys_thr_wake(long id);
int __sys_kldunloadf(int fileid, int flags);
int __sys_audit(const void * __kerncap record, u_int length);
int __sys_auditon(int cmd, void * __kerncap data, u_int length);
int __sys_getauid(uid_t * __kerncap auid);
int __sys_setauid(uid_t * __kerncap auid);
int __sys_getaudit(struct auditinfo * __kerncap auditinfo);
int __sys_setaudit(struct auditinfo * __kerncap auditinfo);
int __sys_getaudit_addr(struct auditinfo_addr * __kerncap auditinfo_addr, u_int length);
int __sys_setaudit_addr(struct auditinfo_addr * __kerncap auditinfo_addr, u_int length);
int __sys_auditctl(const char * __kerncap path);
int __sys__umtx_op(void * __kerncap obj, int op, u_long val, void * __kerncap uaddr1, void * __kerncap uaddr2);
int __sys_thr_new(struct thr_param * __kerncap param, int param_size);
int __sys_sigqueue(pid_t pid, int signum, void * __kerncap value);
int __sys_kmq_open(const char * __kerncap path, int flags, mode_t mode, const struct mq_attr * __kerncap attr);
int __sys_kmq_setattr(int mqd, const struct mq_attr * __kerncap attr, struct mq_attr * __kerncap oattr);
int __sys_kmq_timedreceive(int mqd, char * __kerncap msg_ptr, size_t msg_len, unsigned * __kerncap msg_prio, const struct timespec * __kerncap abs_timeout);
int __sys_kmq_timedsend(int mqd, const char * __kerncap msg_ptr, size_t msg_len, unsigned msg_prio, const struct timespec * __kerncap abs_timeout);
int __sys_kmq_notify(int mqd, const struct sigevent * __kerncap sigev);
int __sys_kmq_unlink(const char * __kerncap path);
void __sys_abort2(const char * __kerncap why, int nargs, void * __kerncap * __kerncap args);
int __sys_thr_set_name(long id, const char * __kerncap name);
int __sys_aio_fsync(int op, struct aiocb * __kerncap aiocbp);
int __sys_rtprio_thread(int function, lwpid_t lwpid, struct rtprio * __kerncap rtp);
int __sys_sctp_peeloff(int sd, uint32_t name);
int __sys_sctp_generic_sendmsg(int sd, void * __kerncap msg, int mlen, const struct sockaddr * __kerncap to, __socklen_t tolen, struct sctp_sndrcvinfo * __kerncap sinfo, int flags);
int __sys_sctp_generic_sendmsg_iov(int sd, struct iovec * __kerncap iov, int iovlen, const struct sockaddr * __kerncap to, __socklen_t tolen, struct sctp_sndrcvinfo * __kerncap sinfo, int flags);
int __sys_sctp_generic_recvmsg(int sd, struct iovec * __kerncap iov, int iovlen, struct sockaddr * __kerncap from, __socklen_t * __kerncap fromlenaddr, struct sctp_sndrcvinfo * __kerncap sinfo, int * __kerncap msg_flags);
ssize_t __sys_pread(int fd, void * __kerncap buf, size_t nbyte, off_t offset);
ssize_t __sys_pwrite(int fd, const void * __kerncap buf, size_t nbyte, off_t offset);
void * __sys_mmap(void * __kerncap addr, size_t len, int prot, int flags, int fd, off_t pos);
off_t __sys_lseek(int fd, off_t offset, int whence);
int __sys_truncate(const char * __kerncap path, off_t length);
int __sys_ftruncate(int fd, off_t length);
int __sys_thr_kill2(pid_t pid, long id, int sig);
int __sys_shm_unlink(const char * __kerncap path);
int __sys_cpuset(cpusetid_t * __kerncap setid);
int __sys_cpuset_setid(cpuwhich_t which, id_t id, cpusetid_t setid);
int __sys_cpuset_getid(cpulevel_t level, cpuwhich_t which, id_t id, cpusetid_t * __kerncap setid);
int __sys_cpuset_getaffinity(cpulevel_t level, cpuwhich_t which, id_t id, size_t cpusetsize, cpuset_t * __kerncap mask);
int __sys_cpuset_setaffinity(cpulevel_t level, cpuwhich_t which, id_t id, size_t cpusetsize, const cpuset_t * __kerncap mask);
int __sys_faccessat(int fd, const char * __kerncap path, int amode, int flag);
int __sys_fchmodat(int fd, const char * __kerncap path, mode_t mode, int flag);
int __sys_fchownat(int fd, const char * __kerncap path, uid_t uid, gid_t gid, int flag);
int __sys_fexecve(int fd, char * __kerncap * __kerncap argv, char * __kerncap * __kerncap envv);
int __sys_futimesat(int fd, const char * __kerncap path, const struct timeval * __kerncap times);
int __sys_linkat(int fd1, const char * __kerncap path1, int fd2, const char * __kerncap path2, int flag);
int __sys_mkdirat(int fd, const char * __kerncap path, mode_t mode);
int __sys_mkfifoat(int fd, const char * __kerncap path, mode_t mode);
int __sys_openat(int fd, const char * __kerncap path, int flag, mode_t mode);
ssize_t __sys_readlinkat(int fd, const char * __kerncap path, char * __kerncap buf, size_t bufsize);
int __sys_renameat(int oldfd, const char * __kerncap old, int newfd, const char * __kerncap new);
int __sys_symlinkat(const char * __kerncap path1, int fd, const char * __kerncap path2);
int __sys_unlinkat(int fd, const char * __kerncap path, int flag);
int __sys_posix_openpt(int flags);
int __sys_gssd_syscall(const char * __kerncap path);
int __sys_jail_get(struct iovec * __kerncap iovp, unsigned int iovcnt, int flags);
int __sys_jail_set(struct iovec * __kerncap iovp, unsigned int iovcnt, int flags);
int __sys_jail_remove(int jid);
int __sys___semctl(int semid, int semnum, int cmd, union semun * __kerncap arg);
int __sys_msgctl(int msqid, int cmd, struct msqid_ds * __kerncap buf);
int __sys_shmctl(int shmid, int cmd, struct shmid_ds * __kerncap buf);
int __sys_lpathconf(const char * __kerncap path, int name);
int __sys___cap_rights_get(int version, int fd, cap_rights_t * __kerncap rightsp);
int __sys_cap_enter(void);
int __sys_cap_getmode(u_int * __kerncap modep);
int __sys_pdfork(int * __kerncap fdp, int flags);
int __sys_pdkill(int fd, int signum);
int __sys_pdgetpid(int fd, pid_t * __kerncap pidp);
int __sys_pselect(int nd, fd_set * __kerncap in, fd_set * __kerncap ou, fd_set * __kerncap ex, const struct timespec * __kerncap ts, const sigset_t * __kerncap sm);
int __sys_getloginclass(char * __kerncap namebuf, size_t namelen);
int __sys_setloginclass(const char * __kerncap namebuf);
int __sys_rctl_get_racct(const void * __kerncap inbufp, size_t inbuflen, void * __kerncap outbufp, size_t outbuflen);
int __sys_rctl_get_rules(const void * __kerncap inbufp, size_t inbuflen, void * __kerncap outbufp, size_t outbuflen);
int __sys_rctl_get_limits(const void * __kerncap inbufp, size_t inbuflen, void * __kerncap outbufp, size_t outbuflen);
int __sys_rctl_add_rule(const void * __kerncap inbufp, size_t inbuflen, void * __kerncap outbufp, size_t outbuflen);
int __sys_rctl_remove_rule(const void * __kerncap inbufp, size_t inbuflen, void * __kerncap outbufp, size_t outbuflen);
int __sys_posix_fallocate(int fd, off_t offset, off_t len);
int __sys_posix_fadvise(int fd, off_t offset, off_t len, int advice);
int __sys_wait6(idtype_t idtype, id_t id, int * __kerncap status, int options, struct __wrusage * __kerncap wrusage, struct __siginfo * __kerncap info);
int __sys_cap_rights_limit(int fd, cap_rights_t * __kerncap rightsp);
int __sys_cap_ioctls_limit(int fd, const u_long * __kerncap cmds, size_t ncmds);
ssize_t __sys_cap_ioctls_get(int fd, u_long * __kerncap cmds, size_t maxcmds);
int __sys_cap_fcntls_limit(int fd, uint32_t fcntlrights);
int __sys_cap_fcntls_get(int fd, uint32_t * __kerncap fcntlrightsp);
int __sys_bindat(int fd, int s, const struct sockaddr * __kerncap name, __socklen_t namelen);
int __sys_connectat(int fd, int s, const struct sockaddr * __kerncap name, __socklen_t namelen);
int __sys_chflagsat(int fd, const char * __kerncap path, u_long flags, int atflag);
int __sys_accept4(int s, struct sockaddr * __kerncap name, __socklen_t * __kerncap anamelen, int flags);
int __sys_pipe2(int * __kerncap fildes, int flags);
int __sys_aio_mlock(struct aiocb * __kerncap aiocbp);
int __sys_procctl(idtype_t idtype, id_t id, int com, void * __kerncap data);
int __sys_ppoll(struct pollfd * __kerncap fds, u_int nfds, const struct timespec * __kerncap ts, const sigset_t * __kerncap set);
int __sys_futimens(int fd, const struct timespec * __kerncap times);
int __sys_utimensat(int fd, const char * __kerncap path, const struct timespec * __kerncap times, int flag);
int __sys_fdatasync(int fd);
int __sys_fstat(int fd, struct stat * __kerncap sb);
int __sys_fstatat(int fd, const char * __kerncap path, struct stat * __kerncap buf, int flag);
int __sys_fhstat(const struct fhandle * __kerncap u_fhp, struct stat * __kerncap sb);
ssize_t __sys_getdirentries(int fd, char * __kerncap buf, size_t count, off_t * __kerncap basep);
int __sys_statfs(const char * __kerncap path, struct statfs * __kerncap buf);
int __sys_fstatfs(int fd, struct statfs * __kerncap buf);
int __sys_getfsstat(struct statfs * __kerncap buf, long bufsize, int mode);
int __sys_fhstatfs(const struct fhandle * __kerncap u_fhp, struct statfs * __kerncap buf);
int __sys_mknodat(int fd, const char * __kerncap path, mode_t mode, dev_t dev);
int __sys_kevent(int fd, const struct kevent * __kerncap changelist, int nchanges, struct kevent * __kerncap eventlist, int nevents, const struct timespec * __kerncap timeout);
int __sys_cpuset_getdomain(cpulevel_t level, cpuwhich_t which, id_t id, size_t domainsetsize, domainset_t * __kerncap mask, int * __kerncap policy);
int __sys_cpuset_setdomain(cpulevel_t level, cpuwhich_t which, id_t id, size_t domainsetsize, domainset_t * __kerncap mask, int policy);
int __sys_getrandom(void * __kerncap buf, size_t buflen, unsigned int flags);
int __sys_getfhat(int fd, char * __kerncap path, struct fhandle * __kerncap fhp, int flags);
int __sys_fhlink(struct fhandle * __kerncap fhp, const char * __kerncap to);
int __sys_fhlinkat(struct fhandle * __kerncap fhp, int tofd, const char * __kerncap to);
int __sys_fhreadlink(struct fhandle * __kerncap fhp, char * __kerncap buf, size_t bufsize);
int __sys_funlinkat(int dfd, const char * __kerncap path, int fd, int flag);
ssize_t __sys_copy_file_range(int infd, off_t * __kerncap inoffp, int outfd, off_t * __kerncap outoffp, size_t len, unsigned int flags);
int __sys___sysctlbyname(const char * __kerncap name, size_t namelen, void * __kerncap old, size_t * __kerncap oldlenp, void * __kerncap new, size_t newlen);
int __sys_shm_open2(const char * __kerncap path, int flags, mode_t mode, int shmflags, const char * __kerncap name);
int __sys_shm_rename(const char * __kerncap path_from, const char * __kerncap path_to, int flags);
int __sys_sigfastblock(int cmd, void * __kerncap ptr);
int __sys___realpathat(int fd, const char * __kerncap path, char * __kerncap buf, size_t size, int flags);
int __sys_close_range(u_int lowfd, u_int highfd, int flags);
int __sys_rpctls_syscall(int op, const char * __kerncap path);
int __sys___specialfd(int type, const void * __kerncap req, size_t len);
int __sys_aio_writev(struct aiocb * __kerncap aiocbp);
int __sys_aio_readv(struct aiocb * __kerncap aiocbp);
int __sys_fspacectl(int fd, int cmd, const struct spacectl_range * __kerncap rqsr, int flags, struct spacectl_range * __kerncap rmsr);
int __sys_sched_getcpu(void);
int __sys_swapoff(const char * __kerncap name, u_int flags);
int __sys_kqueuex(u_int flags);
int __sys_membarrier(int cmd, unsigned flags, int cpu_id);
int __sys_timerfd_create(int clockid, int flags);
int __sys_timerfd_gettime(int fd, struct itimerspec * __kerncap curr_value);
int __sys_timerfd_settime(int fd, int flags, const struct itimerspec * __kerncap new_value, struct itimerspec * __kerncap old_value);
__END_DECLS

#endif /* __LIBSYS_H_ */
