.PATH: ${SYSDIR}/dev/sift/ace2_syncpoint

KMOD=	ace2_syncpoint

SRCS=	ace2_syncpoint.c \
	ace2_syncpoint_dev.c \
	ace2_syncpoint_module.c \
	ace2_syncpoint_sysctl.c \
	ace2_syncpoint_test.c

.include <bsd.kmod.mk>
