.\"
.\" Copyright (c) 2018 Edward Tomasz Napierala <en322@cl.cam.ac.uk>
.\" All rights reserved.
.\"
.\" This software was developed by SRI International and the University of
.\" Cambridge Computer Laboratory under DARPA/AFRL contract (FA8750-10-C-0237)
.\" ("CTSRD"), as part of the DARPA CRASH research programme.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd April 30, 2018
.Dt COCALL 2
.Os
.Sh NAME
.Nm COCALL
.Nd accept a colocated call
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In unistd.h
.Ft int
.Fn coaccept "void * __capability code" "void * __capability data" "void *data" "size_t len"
.Sh DESCRIPTION
The
.Fn coaccept
function accepts a colocated call.
Before passing the execution to the callee, at most
.Fa len
bytes pointed to by
.Fa data
will be copied from buffer provided by the caller; before returning the data
will be copied back to the caller.
.Pp
The
.Ar code
and
.Ar data
arguments must point to a sealed capability pair obtained from
.Xr cosetup 2 .
.Sh RETURN VALUES
.Rv -std coaccept
.Sh ERRORS
The
.Fn coaccept
system call
will fail if:
.Bl -tag -width Er
.It Bq Er EINVAL
The
.Fa code or
.Fa data
arguments are invalid.
.It Bq Er EFAULT
The
.Fa data
argument
points outside the process's allocated address space.
.El
.Sh SEE ALSO
.Xr coexec 2 ,
.Xr cosetup 2 ,
.Xr coregister 2 ,
.Xr colookup 2 ,
.Xr coaccept 2 ,
.Xr coaccept 2
.Sh HISTORY
The
.Fn coaccept
system call first appeared in
.Tn CheriBSD .
.Sh AUTHORS
.An -nosplit
These functions were created by
.An Edward Tomasz Napierala Aq Mt trasz@FreeBSD.org
at the University of Cambridge Computer Laboratory under DARPA/AFRL contract
(FA8750-10-C-0237) ("CTSRD"), as part of the DARPA CRASH research programme.
