.\"
.\" Copyright (c) 2018 Edward Tomasz Napierala <en322@cl.cam.ac.uk>
.\" All rights reserved.
.\"
.\" This software was developed by SRI International and the University of
.\" Cambridge Computer Laboratory under DARPA/AFRL contract (FA8750-10-C-0237)
.\" ("CTSRD"), as part of the DARPA CRASH research programme.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd March 17, 2022
.Dt COGETPID 2
.Os
.Sh NAME
.Nm COGETPID
.Nd get calling process identification
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In unistd.h
.Ft int
.Fn cogetpid "void * __capability cookie" "pid_t *pidp"
.Ft pid_t
.Fn cogetpid2 "void * __capability target"
.Sh DESCRIPTION
The
.Fn cogetpid
writes PID of the calling process into the variable pointed at by
.Ar pidp .
It is intended for use on the callee side, after successfully returning from
.Xr coaccept 2 .
.Pp
It is a system call, so it is relatively slow.
Users are expected to cache the PID, by keeping a dictionary of (cookie, pid) pairs, only calling
.Fn cogetpid
when the value of the cookie - filled in by
.Xr coaccept 2 -
cannot be found there.
.Sh RETURN VALUES
.Rv -std cogetpid
.Sh ERRORS
The
.Fn cogetpid
system call
will fail if:
.Bl -tag -width Er
.It Bq Er EFAULT
The
.Fa pidp
argument
points outside the process's allocated address space.
.It Bq Er ESRCH
Unable to determine identity of the caller.
.El
.Sh SEE ALSO
.Xr copong 1 ,
.Xr cocall 2 ,
.Xr coexec 2 ,
.Xr cosetup 2 ,
.Xr coregister 2 ,
.Xr colookup 2 ,
.Xr coaccept 2
.Sh HISTORY
The
.Fn coaccept
system call first appeared in
.Tn CheriBSD .
.Sh AUTHORS
.An -nosplit
These functions were created by
.An Edward Tomasz Napierala Aq Mt trasz@FreeBSD.org
at the University of Cambridge Computer Laboratory under DARPA/AFRL contract
(FA8750-10-C-0237) ("CTSRD"), as part of the DARPA CRASH research programme.
