# $FreeBSD$

.PATH:	${SRCTOP}/sys/arm64/coresight

KMOD	= coresight
SRCS	=			\
	coresight.c		\
	coresight_acpi.c	\
	coresight_cmd.c		\
	coresight_fdt.c		\
	coresight_if.c		\
	coresight_if.h

.include <bsd.kmod.mk>
