.\" Copyright (c) 2025 Capabilities Limited
.\"
.\" SPDX-License-Identifier: BSD-2-Clause
.\"
.\" This software was developed by SRI International, the University of
.\" Cambridge Computer Laboratory (Department of Computer Science and
.\" Technology), and Capabilities Limited under Defense Advanced Research
.\" Projects Agency (DARPA) Contract No. FA8750-24-C-B047 ("DEC").
.\"
.Dd December 9, 2025
.Dt ACE2_SYNCPOINT 4
.Os
.Sh NAME
.Nm ace2_syncpoint
.Sh SYNOPSIS
.In sys/dev/sift/ace2_syncpoint/ace2_syncpoint.h
.Ft uint64_t
.Fn ace2_syncpoint "const char *label" "const char *fmt" "..."
.Ft void
.Fn ace2_observe "uint64_t seq_id" "const char *label" "const char *fmt" "..."
.Sh DESCRIPTION
This module implements a
.Em syncpoint
abstraction that enables kernel components to notify userspace of an event and
then await acknowledgment.
This mechanism is used in the evaluation of the DARPA CPM program.
.Pp
The
.Nm module provides four interfaces enabling kernel-user syncronization:
.Bl -bullet
.It
Kernel programming interfaces identifying "sync points"
.It
Kernel console output describing kernel events
.It
Device nodes created for each event to enable acknowledgment
.It
Sysctl nodes configuring and monitoring the module
.El
.Sh KERNEL PROGRAMMING INTERFACES
.Fn ace2_syncpoint
creates a new syncpoint instance, suspending the current thread and notifying
userspace with a new unique ID associated with the argument
.Fa label .
When the syncpoint is completed, the ID is returned so that it can be passed
as an argument to
.Fn ace2_observe .
Additional output is specified by the format string
.Fa fmt
and additional arguments, which will be printed to the kernel console.
.Pp
.Fn ace2_observe
generates a further line of console output accepting the argument
.Fa seq_id
returned by a previous call to
.Fn ace2_syncpoint,
the corresponding
.Fa label ,
a format string passed as
.Fa fmt
and any additional output.
.Sh KERNEL CONSOLE OUTPUT
.Nm ace2_syncpoint
kernel console ouput generated by
.Fn ace2_syncpoint
and
.Fn ace2_observe
is a part of the defined kernel interface.
.Ss ace2_syncpoint
.Fn ace2_syncpoint
displays the following fields:
.Pp
.Bl -tag -width ACE2_SYNC_BARRIER
.It ACE2_SYNC_BARRIER
Indicates that a barrier has been entered.
.It label:seq_id
The
.Fa label
passed to
.Fn ace2_syncpoint
and the generated ID for the syncpoint instance.
.It file:line:func
The source-code file, line number, and function that called
.Fn ace2_syncpoint .
.El
.Pp
These are followed by any additional printable arguments passed to
.Fn ace2_syncpoint .
If
.Fn ace2_syncpoint
is called with these arguments:
.Bd -literal -offset indent
id = ace2_syncpoint("example1", "example %d\n", 1);
.Ed
.Pp
This will generate the following output:
.Pp
.Bd -literal -offset indent
ACE2_SYNC_BARRIER example1:1 /usr/src/sys/dev/sift/ace2_syncpoint/ace2_syncpoint_test.c:35:syncpoint_example1 example 1
.Ed
.Pp
.Ss ace2_observe
.Fn ace2_observe
displays the following fields:
.Bl -tag -width ACE2_SYNC_PASSED
.It ACE2_SYNC_PASSED
Indicates that a barrier has been passed.
.It label:seq_id
The
.Fa label
passed to
.Fn ace2_syncpoint
and the generated ID for the syncpoint instance.
.It file:line:func
The source-code file, line number, and function that called
.Fn ace2_observe .
.El
.Pp
These are followed by any additional printable arguments passed to
.Fn ace2_observe .
If
.Fn ace2_syncpoint
is called with these arguments:
.Bd -literal -offset indent
ace2_observe(id, "example1", "%d", 1);
.Ed
.Pp
This will generate the following output:
.Pp
.Bd -literal -offset indent
ACE2_SYNC_PASSED example1:1 /usr/src/sys/dev/sift/ace2_syncpoint/ace2_syncpoint_test.c:35:syncpoint_example1 example 1
.Ed
.Sh DEVICE NODES
When
.Fn ace2_syncpoint
is calls, a new device
.Pa /dev/ace2_syncpoint/ID
is created, where
.Em ID
is the unique ID assigned to the syncpoint instance.
When the syncpoint is acknowledged, this device is removed.
.Pp
To query information on the syncpoint, the device may be opened and read.
Typical contents are:
.Pp
.Bd -literal -offset indent
BARRIER_ID: 2
STATUS: WAITING
LABEL: example1
FILE: /usr/src/sys/dev/sift/ace2_syncpoint/ace2_syncpoint_test.c
LINE: 35
FUNC: syncpoint_example1
.Ed
.Pp
The following fields are displayed:
.Bl -tag -width BARRIER_ID
.It BARRIER_ID
The unique syncpoint instance ID.
.It STATUS
The current syncpoint status, which may be
.Em WAITING
or
.Em COMPLETED .
.It LABEL
The
.Fa label
argument passed to
.Fn ace2_syncpoint .
.It FILE
The source-code file where
.Fn ace2_syncpoint
was called.
.It LINE
The source-code line nuber where
.Fn ace2_syncpoint
was called.
.It FUNC
The source-code function where
.Fn ace2_syncpoint
was called.
.El
.Pp
File reads are idempotant and may be performed by more than one process until
the syncpoint has been acknowledged.
.Pp
To complete a syncpoint, the device may be opened and written.
A single-byte read is sufficient to complete the syncpoint.
.Sh SYSCTL NODES
Several sysctl nodes are defined for the module, including:
.Bl -tag -width dev.ace2.syncpoint.enabled
.It dev.ace2.syncpoint.list
Generate a text description of all currently waiting syncpoints.
This is best dumped using the
.Pa "sysctl -b"
command.
.It dev.ace2.syncpoint.count
Returns the current number of waiting syncpoints.
.It dev.ace2.syncpoint.enabled
Enables syncpoints; if this is disabled then
.Fn ace2_syncpoint
returns immediately without creating a syncpoint.
.El
.Sh FILES
.Bl -tag -width "/dev/ace2_syncpoint" -compact
.It Pa /dev/ace2_syncpoint
.El
.Sh AUTHORS
.An -nosplit
This driver was written by
.An Robert N. M. Watson Aq Mt robert.watson@cl.cam.ac.uk .
.Pp
This software was developed by SRI International, the University of
Cambridge Computer Laboratory (Department of Computer Science and
Technology), and Capabilities Limited under Defense Advanced Research
Projects Agency (DARPA) Contract No. FA8750-24-C-B047 ("DEC").
