#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ldconfig
# REQUIRE: FILESYSTEMS
# BEFORE:  DAEMON

. /etc/rc.subr

name="ldconfig"
desc="Configure the shared library cache"
ldconfig_command="/sbin/ldconfig"
start_cmd="ldconfig_start"
stop_cmd=":"

ldconfig_start()
{
	local _files _ins

	_ins=
	ldconfig=${ldconfig_command}
	checkyesno ldconfig_insecure && _ins="-i"
	if [ -x "${ldconfig_command}" ]; then
		_LDC="/lib /usr/lib"
		for i in ${ldconfig_local_dirs}; do
			if [ -d "${i}" ]; then
				_files=`find ${i} -type f`
				if [ -n "${_files}" ]; then
					ldconfig_paths="${ldconfig_paths} `cat ${_files} | sort -u`"
				fi
			fi
		done
		for i in ${ldconfig_paths} /etc/ld-elf.so.conf; do
			if [ -r "${i}" ]; then
				_LDC="${_LDC} ${i}"
			fi
		done
		startmsg 'ELF ldconfig path:' ${_LDC}
		${ldconfig} -elf ${_ins} ${_LDC}

		machine_arch=$(sysctl -n hw.machine_arch)

		case ${machine_arch} in
		aarch64c)
			ldconfigc18n_hints_file="/var/run/ld-elf-c18n.so.hints"
			_LDC="/usr/lib/c18n ${_LDC}"
			startmsg 'Library-based compartmentalization ldconfig path:' ${_LDC}
			${ldconfig} ${_ins} -f ${ldconfigc18n_hints_file} ${_LDC}
			;&
			# FALLTHROUGH
		riscv64c)
			for i in ${ldconfig_local64_dirs}; do
				if [ -d "${i}" ]; then
					_files=`find ${i} -type f`
					if [ -n "${_files}" ]; then
						ldconfig64_paths="${ldconfig64_paths} `cat ${_files} | sort -u`"
					fi
				fi
			done
			_LDC=""
			for i in ${ldconfig64_paths}; do
				if [ -r "${i}" ]; then
					_LDC="${_LDC} ${i}"
				fi
			done
			check_startmsgs &&
			    echo '64-bit compatibility ldconfig path:' ${_LDC}
			${ldconfig} -64 ${_ins} ${_LDC}
			;;
		amd64|mips64|powerpc64)
			for i in ${ldconfig_local32_dirs}; do
				if [ -d "${i}" ]; then
					_files=`find ${i} -type f`
					if [ -n "${_files}" ]; then
						ldconfig32_paths="${ldconfig32_paths} `cat ${_files} | sort -u`"
					fi
				fi
			done
			_LDC=""
			for i in ${ldconfig32_paths}; do
				if [ -r "${i}" ]; then
					_LDC="${_LDC} ${i}"
				fi
			done
			startmsg '32-bit compatibility ldconfig path:' ${_LDC}
			${ldconfig} -32 ${_ins} ${_LDC}
			;;
		esac

	fi
}

load_rc_config $name
run_rc_command "$1"
