#!/bin/sh
#
#

# PROVIDE: ldconfig
# REQUIRE: FILESYSTEMS
# BEFORE:  DAEMON

. /etc/rc.subr

name="ldconfig"
desc="Configure the shared library cache"
ldconfig_command="/sbin/ldconfig"
start_cmd="ldconfig_start"
stop_cmd=":"

ldconfig_paths()
{
	local _dirs _files _ii _ldconf _ldpaths _paths

	_dirs="${1}"
	_paths="${2}"
	_ldpaths="${3}"
	_ldconf="${4}"

	for _ii in ${_dirs}; do
		if [ -d "${_ii}" ]; then
			_files=`find ${_ii} -type f`
			if [ -n "${_files}" ]; then
				_paths="${_paths} `cat ${_files} | sort -u`"
			fi
		fi
	done
	for _ii in ${_paths} ${_soconf}; do
		if [ -r "${_ii}" ]; then
			_ldpaths="${_ldpaths} ${_ii}"
		fi
	done

	echo "${_ldpaths}"
}

ldconfig_start()
{
	local _files _ins

	_ins=
	ldconfig=${ldconfig_command}
	checkyesno ldconfig_insecure && _ins="-i"
	if [ -x "${ldconfig_command}" ]; then
		_LDC=$(ldconfig_paths "${ldconfig_local_dirs}" \
		    "${ldconfig_paths}" "/lib /usr/lib" "/etc/ld-elf.so.conf")
		startmsg 'ELF ldconfig path:' ${_LDC}
		${ldconfig} -elf ${_ins} ${_LDC}

		machine_arch=$(sysctl -n hw.machine_arch)

		case ${machine_arch} in
		aarch64c)
			_LDC="/usr/lib/c18n ${_LDC}"
			startmsg 'Library-based compartmentalization ldconfig path:' ${_LDC}
			${ldconfig} -f /var/run/ld-elf-c18n.so.hints ${_ins} ${_LDC}
			;&
			# FALLTHROUGH
		riscv64c)
			_LDC=$(ldconfig_paths "${ldconfig_local64_dirs}" \
			    "${ldconfig64_paths}" "" "")
			startmsg '64-bit compatibility ldconfig path:' ${_LDC}
			${ldconfig} -64 ${_ins} ${_LDC}
			;;
		esac
		case ${machine_arch} in
		aarch64*|amd64|powerpc64)
			_LDC=$(ldconfig_paths "${ldconfig_local32_dirs}" \
			    "${ldconfig32_paths}" "" "")
			startmsg '32-bit compatibility ldconfig path:' ${_LDC}
			${ldconfig} -32 ${_ins} ${_LDC}
			;;
		esac

	fi
}

load_rc_config $name
run_rc_command "$1"
