#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: os-release
# REQUIRE: mountcritremote FILESYSTEMS
# BEFORE:  LOGIN

. /etc/rc.subr

: ${osrelease_file:=/var/run/os-release}
: ${osrelease_perms:=444}
name="osrelease"
desc="Update ${osrelease_file}"
rcvar="osrelease_enable"
start_cmd="osrelease_start"
stop_cmd=":"

osrelease_start()
{
	local _version _version_id

	startmsg -n "Updating ${osrelease_file} "
	_version=$(freebsd-version -u)
	_version_id=${_version%%[^0-9.]*}
	t=$(mktemp -t os-release)
	cat > "$t" <<-__EOF__
		NAME=CheriBSD
		VERSION="$_version"
		VERSION_ID="$_version_id"
		ID=cheribsd
		ID_LIKE=freebsd
		ANSI_COLOR="0;31"
		PRETTY_NAME="CheriBSD $_version"
		CPE_NAME="cpe:/o:freebsd:freebsd:$_version_id"
		HOME_URL="https://www.cheribsd.org/"
		BUG_REPORT_URL="https://github.com/CTSRD-CHERI/cheribsd/issues"
__EOF__
	install -C -o root -g wheel -m ${osrelease_perms} "$t" "${osrelease_file}"
	rm -f "$t"
	startmsg 'done.'
}

load_rc_config $name
run_rc_command "$1"
